<?xml version="1.0" encoding="UTF-8"?><xsd:schema targetNamespace="http://ei/core/business_event_key" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="BusinessEventKey">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="BusinessEventKeyName" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the name of a business event key.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="BusinessEventKeyValue" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the value of a business event key.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="BusinessEventKeyDate" type="xsd:date">
				<xsd:annotation>
          <xsd:documentation>This element contains a date of a business event.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="BusinessEventKeyAmount" type="xsd:decimal">
				<xsd:annotation>
          <xsd:documentation>This element contains the an amount associated with the business event.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="BusinessEventKeyIndicator" type="xsd:boolean">
				<xsd:annotation>
          <xsd:documentation>This element contains an indicator for a business event.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>