<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://ei/core/component_property">
	<xsd:complexType name="ComponentProperty">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="ComponentPropertyName"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains the name of the property of a component such as an application or service.
For example: Pacing Level, RepositoryBaseURL
</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ComponentPropertyValue"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains the value of the property of a component such as an application or service.
For example: 7 http://surety.dav.chubb/webdav.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="ComponentPropertySequenceNumber" type="xsd:integer"><xsd:annotation><xsd:documentation>This element contains a generated unique sequence number assigned to a particular component property.</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>
