<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ei/core/document_set"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:bons0="http://ei/core/managed_document">
	<xsd:import schemaLocation="ManagedDocument.xsd"
		namespace="http://ei/core/managed_document">
	</xsd:import>
	<xsd:complexType name="DocumentSet">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="ManagedDocument"
				type="bons0:ManagedDocument" maxOccurs="unbounded">
			</xsd:element>
			<xsd:element minOccurs="0" name="DocumentSetNumber"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains a number assigned to this document set.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="DocumentSetName"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains the name assigned to the document set.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="DocumentSetTypeName"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains the type name of the document set.</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>