<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://ei/core/extended_insurer"
	xmlns:bons0="http://ei/core/insurerx1">
	<xsd:import schemaLocation="InsurerX1.xsd"
		namespace="http://ei/core/insurerx1">
	</xsd:import>
	<xsd:complexType name="ExtendedInsurer">
		<xsd:complexContent>
			<xsd:extension base="bons0:Insurer">
				<xsd:sequence>
					<xsd:element minOccurs="0"
						name="InsurerIncorporatedDate" type="xsd:date">
						<xsd:annotation><xsd:documentation>This element contains the date the Insurer was first established.

</xsd:documentation></xsd:annotation>
					</xsd:element>
					<xsd:element minOccurs="0"
						name="InsurerCommencementDate" type="xsd:date">
						<xsd:annotation><xsd:documentation>This element contains the date that Chubb begins to manage the Insurer.
</xsd:documentation></xsd:annotation>
					</xsd:element>
					<xsd:element minOccurs="0"
						name="InsurerCancellationDate" type="xsd:date">
						<xsd:annotation><xsd:documentation>This element contains the date that Chubb ceases to manage the Insurer.
</xsd:documentation></xsd:annotation>
					</xsd:element>
					<xsd:element minOccurs="0"
						name="ActiveInsurerIndicator" type="xsd:string"><xsd:annotation><xsd:documentation>This specifies whether the Insurer is active, which means the Insurer is still included in Chubb Systems.
Valid values for this element are 'Y' or 'N'.  </xsd:documentation></xsd:annotation>
					</xsd:element>
					<xsd:element minOccurs="0"
						name="LicenseInsurerIndicator" type="xsd:string"><xsd:annotation><xsd:documentation>This element indentifies if the company is now or was ever licensed to issue policies.
Valid values for this element are 'Y' or 'N'.</xsd:documentation></xsd:annotation>
					</xsd:element>
					<xsd:element minOccurs="0"
						name="InsurerDomicileCountryCode" type="xsd:string">
						<xsd:annotation><xsd:documentation>This element contains the country the company is registered or incorporated.
</xsd:documentation></xsd:annotation>
					</xsd:element>
					<xsd:element minOccurs="0"
						name="InsurerDomicileStateOrProvinceCode" type="xsd:string"><xsd:annotation><xsd:documentation>This element contains the state within the United States the Insurer is incorporated.
</xsd:documentation></xsd:annotation>
					</xsd:element>
					<xsd:element minOccurs="0"
						name="InsurerReportingCurrencyCode" type="xsd:string"><xsd:annotation><xsd:documentation>This element contains the currency in which a Chubb Insurer (Writing Company) does it's reporting to regulatory bureaus.
</xsd:documentation></xsd:annotation>
					</xsd:element>
				</xsd:sequence>

			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:schema>
