<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://ei/core/line_of_business_tax_ratex1">
	<xsd:complexType name="LineOfBusinessTaxRate">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="TaxRateLineOfBusinessCode"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains a code which indentifies the line of business.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="TaxRateLineOfBusinessName"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains the line of business name, as assigned by the tax rate service.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="LineOfBusinessTaxRate"
				type="xsd:decimal">
				<xsd:annotation><xsd:documentation>This element contains the Tax Rate for the Line Of Business.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="LineofBusinessTaxRateWithCollectionFee" type="xsd:decimal">
				<xsd:annotation><xsd:documentation>This element contains the line of business tax rate with the allowed collection fee included.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ComplexTaxRate"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains a complex tax rate.</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>
