<?xml version="1.0" encoding="UTF-8"?><xsd:schema targetNamespace="http://ei/core/loss_history_cause_of_loss_payment" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="LossHistoryCauseOfLossPayment">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="SourceSystemCauseOfLossCode" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a code that identifies the cause of loss as it is known by the source system.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="SourceSystemCauseOfLossName" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>This element contains a name that describes the cause of loss as it is known by the source system.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="CauseOfLossStatusCode" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a code that identifies the status of the cause of loss.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0" name="CauseOfLossStatusName" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>This element contains a name that describes the status of the cause of loss.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="CauseOfLossPaidAmount" type="xsd:decimal">
				<xsd:annotation>
          <xsd:documentation>This element contains the amount paid for a cause of loss.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>