<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ei/core/survey_contactx1"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:bons1="http://ei/core/business_contactx1">
	<xsd:import schemaLocation="BusinessContactX1.xsd"
		namespace="http://ei/core/business_contactx1">
	</xsd:import>
	<xsd:complexType name="SurveyContact">
		<xsd:sequence>

			<xsd:element maxOccurs="unbounded" minOccurs="0"
				name="BusinessContact" type="bons1:BusinessContact">
			</xsd:element>
			<xsd:element minOccurs="0" name="SurveyContactTypeName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the name of the type of survey contact.
Some valid options for this element are 'Producer', 'Insured', 'Location'.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>