<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
	targetNamespace="http://ei/core/bm_certificate_jurisdiction_fee_summary"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="BMCertificateJurisdictionFeeSummary">
		<xsd:sequence>

			<xsd:element minOccurs="0" name="BMJurisdictionTypeName"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains the type of jurisdiction associated with the Boiler &amp; Machinery certificate fees.
Valid values for this element include: State and City.  </xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="BMJurisdictionCode"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains the code associated with the jurisdiction where the boiler and machinery equipment is located.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="BMJurisdictionName"
				type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element contains the jurisdiction where the boiler and machinery equipment is located.</xsd:documentation></xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0"
				name="BMJurisdictionPostalStateAbbreviation" type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element contains the postal state abbreviation where the Boiler or Machinery is located.  </xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ISOCountryCode"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element is the abbreviation used by the International Standards Organization (ISO) that identifies a country, nation or political state.
The E1T00101 Corporate Table contains valid values for this element in the &quot;ISO_CNTRY_C&quot; column. </xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="JurisdictionNumberOfObjectsCount" type="xsd:integer"><xsd:annotation><xsd:documentation>This element contains the number of objects in the Jurisdiction.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="TotalJurisdictionCertificateFee" type="xsd:decimal">
				<xsd:annotation>
          
        <xsd:documentation>This element contains the fee associated with the inspection certificates in this Jurisdiction, which can be a City or State.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="TotalJurisdictionHandlingFee" type="xsd:decimal">
				<xsd:annotation>
          
        <xsd:documentation>This element contains the handling fee associated with the inspection certificates in this Jurisdiction, which can be a City or State.</xsd:documentation></xsd:annotation>
			</xsd:element>




			<xsd:element minOccurs="0" name="TotalJurisdictionFee"
				type="xsd:decimal">
				<xsd:annotation><xsd:documentation>This element contains the sum of the Jurisidiction Handling Fee and Jurisdiction Certificate Fee, which can be a City or State.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="FeeCurrencyCode"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains a code which indentifies the currency of the fee amount.</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>