<?xml version="1.0" encoding="UTF-8"?><xsd:schema targetNamespace="http://ei/core/business_event_information" xmlns:bons1="http://ei/core/business_event_key" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:import namespace="http://ei/core/business_event_key" schemaLocation="BusinessEventKey.xsd"/>
	<xsd:complexType name="BusinessEventInformation">
		<xsd:sequence>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="BusinessEventKey" type="bons1:BusinessEventKey">
			</xsd:element>
			<xsd:element minOccurs="0" name="BusinessEventTypeName" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>This element contains the name of the type of business event.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="BusinessEventName" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>This element contains the name assigned to the business event.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>