<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://ei/core/business_unit_information">
	<xsd:complexType name="BusinessUnitInformation">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="BusinessUnitCode"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains a code for the business unit, a corporate entity or business group.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="BusinessUnitAbbreviation"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains the abbreviation for the business unit, a corporate entity or business group.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="BusinessUnitName"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains the name of the business unit, a corporate entity or business group.</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>
