<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ei/core/claim_life_cycle_stage"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:bons0="http://ei/core/claim_life_cycle_stage_property">
	<xsd:import schemaLocation="ClaimLifeCycleStageProperty.xsd"
		namespace="http://ei/core/claim_life_cycle_stage_property">
	</xsd:import>
	<xsd:complexType name="ClaimLifeCycleStage">
		<xsd:sequence>
			<xsd:element minOccurs="0"
				name="ClaimLifeCycleStageProperty"
				type="bons0:ClaimLifeCycleStageProperty" maxOccurs="unbounded">
			</xsd:element>
			<xsd:element minOccurs="0"
				name="ClaimLifeCycleStageSequenceNumber" type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains the sequence number of the claim lifecycle stage.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ClaimLifeCycleStageName"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains the name of the claim life cycle stage.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="ClaimLifeCycleStageDescription" type="xsd:string"><xsd:annotation><xsd:documentation>This element describes the claim life cycle stage.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="ClaimLifeCycleStageInsuredText" type="xsd:string">
				<xsd:annotation><xsd:documentation>This element describes the responsibilities of the Insured at this stage of the claim life cycle.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="ClaimLifeCycleStageChubbText" type="xsd:string">
				<xsd:annotation><xsd:documentation>This element describes the responsibilities of Chubb at this stage of the claim life cycle.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="CurrentClaimLifeCycleStageIndicator" type="xsd:boolean">
				<xsd:annotation><xsd:documentation>This element indicates if this is the current claim life cycle stage. </xsd:documentation></xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0"
				name="ClaimLifeCycleStageDocumentURL" type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains a link to a document about this claim life cycle stage.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="ClaimLifeCycleStageWebsiteURL" type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains a link to a website about this claim life cycle stage.</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>