<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
	targetNamespace="http://ei/core/client_update_process_information"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="ClientUpdateProcessInformation">
		<xsd:annotation>
      <xsd:documentation>This element contains the unique number that identifies that transaction, as it is known by the source system.</xsd:documentation>
    </xsd:annotation>
		<xsd:sequence>
			<xsd:element minOccurs="0" name="SourceSystemTransactionId"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains the transaction id as it is known by the sourcre system.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ProcessClassificationCode"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element allows the source of the data to be classified so a specific action(process) can be taken based on what system and/or CCM is supplying the data.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ProcessClassificationName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element allows the source of the data to be classified so a specific action(process) can be taken based on whay system and/or CCM is supplying the data.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ResumeActivityName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element specifies the name of the activity being resumed by the process.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="InitiatingProcessTypeName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the type of the process that is calling this business process or service. Some valid values include ‘Online’, ‘Batch’, and ‘Rewrite’.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PolicyNumber"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element identifies an insurance contract.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="InceptionDate"
				type="xsd:date">
				<xsd:annotation>
          <xsd:documentation>This element specifies the inception date of a policy term. </xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="TransactionBypassOrderLogicIndicator" type="xsd:boolean">
				<xsd:annotation>
          <xsd:documentation>This element indicates if the out of order logic should be bypassed when processing this transaction</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="TransactionBypassProcessIndicator" type="xsd:boolean">
				<xsd:annotation>
          <xsd:documentation>This element indicates this transaction needs to be sent thru to provider and bypass the rest of the process.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0" name="SystemId"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element identifies internal/external sources of information.
This is also known as the System Source Code. 
The Corporate table E1T00871 contains the valid values for this element in the "SYS_SRC_C"  column.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ServiceConsumerSystemId"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element identifies internal/external sources of information, from the system that directly invokes an ICC service.
This is also known as the System Source Code. 
The Corporate table E1T00871 contains the valid values for this element in the &quot;SYS_SRC_C&quot;  column. </xsd:documentation></xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0" name="UserId"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element is used to sign on to an application.  
This is also known as RACFId.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="SyntheticTransactionTypeCode" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element refers to a service functional test which serves no business value.  The intention of the test is to confirm the service is functioning properly.    Some services can be tested fully.
Other services, such as those that would update a database can only perform a simple ping test.
Valid values include 'Full' or 'Simple Ping'.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="SourceSystemKeyId"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the key to the transaction of the policy system or data entry system that originated the transaction.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="TransactionLogUniqueId"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a unique id used to log a transaction.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ProcessStartTimestamp"
				type="xsd:dateTime">
				<xsd:annotation>
          <xsd:documentation>This element contains the timestamp of the process was started.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0"
				name="AdditionalOptionsText" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element specifies which options the consumer wants executed on this service.   
For example, this could be used for enrichment.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="MessagePriorityNumber"
				type="xsd:int"><xsd:annotation><xsd:documentation>This element contains a priority that is assigned to the message, which will be interpreted by the business process in which it is used.</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>