<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://ei/core/currency_exchange_rate">
	<xsd:complexType name="CurrencyExchangeRate">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="CurrencyExchangeRate" type="xsd:decimal">
				<xsd:annotation>
          <xsd:documentation>This element is used in a calculation to convert a money amount from one currency to another currency. </xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ExchangeRateDate" type="xsd:date">
				<xsd:annotation>
          <xsd:documentation>This element identifies the effective date of the currency exchange rate. </xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="FromISOCurrencyCode" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the code used by the International Standards Organization (ISO) to identify a currency.  This element specifically represents the 'from' code which will be used by the service  to provide a currency exchange rate based on the from/to ISO currency codes.

The E1T01031  Corporate Table contains valid values for this element in the "ISO_CURNCY_C " column. </xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ToISOCurrencyCode" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>This element contains the code used by the International Standards Organization (ISO) to identify a currency.  This element specifically represents the 'to' code which will be used by the service  to provide a currency exchange rate based on the from/to ISO currency codes.

The E1T01031  Corporate Table contains valid values for this element in the "ISO_CURNCY_C " column. </xsd:documentation>
        </xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>
