<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ei/core/customer_segment"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="CustomerSegment">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="CustomerSegmentCode"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a code identifies a customer segment.  
Personal Lines Customers can be rated as VIP or Signature if their premium exceeds a certain threshold.
Some valid values include 'VP'- "Very Important Person" or "SC"- Signature Customer.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="CustomerSegmentName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a name that identifies a customer segment.   Personal Lines Customers can be rated as VIP or Signature if their premium exceeds a certain threshold.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="CustomerSegmentSourceCode"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a code that identifies the source of the customer segment data.
Some valid personal lines values include 'U'-PLUW, 'B'- PINPOINT, 'P'- Premium, 'M'- MPII Checkbox-indicator, or space.
</xsd:documentation>
        </xsd:annotation>
			</xsd:element>




			<xsd:element minOccurs="0" name="BusinessUnitName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the name of the business unit, a corporate entity or business group.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>



			<xsd:element minOccurs="0"
				name="CustomerSegmentSourceOverrideIndicator" type="xsd:boolean"><xsd:annotation><xsd:documentation>This element specifies whether the source of the policy customer segment assignment can be overridden.
</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>