<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ei/core/endpoint_informationx1"
	xmlns:bons1="http://ei/core/endpoint_informationx1"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="EndpointInformation">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="ServiceInterfaceName"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element identifies the name of the service interface (e.g. ProducerValidationPRD1X2).</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="TransportProtocol"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This elements desribes the protocol used, such as MQ, HTTP, HTTPS, JMS.
</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ServiceVersionNumber"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element identifies a particular verson of the service (e.g. 2.1 but could be more complex to include TestingIMEX)</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="EnvironmentName"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element represents the name of the environment where a system executes.</xsd:documentation></xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0" name="EndpointURL"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element represents the Uniform Resource Language(URL) of the service to be invoked. It is the physical address 
used when calling a service.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="NumberOfSecondsURLExpires"
				type="xsd:integer">
				<xsd:annotation>
          <xsd:documentation>This element represents the number of seconds after which the URL expires at client cache. Sent via service response. 
Zero implies to use a common system value.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0"
				name="Parameter">
				<xsd:annotation>
          <xsd:documentation>This element contains name-value pairs that can be used for endpoint parameters.</xsd:documentation>
        </xsd:annotation>
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="xsd:string">
							<xsd:attribute name="Name"
								type="xsd:string" />
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>