<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ei/core/event_date_time"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="EventDateTime">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="EventName"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element describes the name of the event.</xsd:documentation></xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0" name="EventDateTime"
				type="xsd:dateTime">
				<xsd:annotation><xsd:documentation>This element identifies the dateTime value associated with the EventName.</xsd:documentation></xsd:annotation>
			</xsd:element>

		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>