<?xml version="1.0" encoding="UTF-8"?><xsd:schema targetNamespace="http://ei/core/extended_insurance_admin_role" xmlns:bons1="http://ei/core/insurance_admin_role" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:import namespace="http://ei/core/insurance_admin_role" schemaLocation="InsuranceAdminRole.xsd"/>
	<xsd:complexType name="ExtendedInsuranceAdminRole">
		<xsd:complexContent>
			<xsd:extension base="bons1:InsuranceAdminRole">
				<xsd:sequence>



					<xsd:element minOccurs="0" name="AdminRoleRelatedCode" type="xsd:string">
						<xsd:annotation>
          <xsd:documentation>This element contains another related code for the Admin Role.  The type of related code will vary based on the Admin Role Type Code. 
The E1TA0161 Corporate Table contains valid values for this element in the "RLTD_C" column.</xsd:documentation>
        </xsd:annotation>
					</xsd:element>


				</xsd:sequence>

			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:schema>