<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
	targetNamespace="http://ei/core/get_access_source_information"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="GetAccessSourceInformation">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="SourceURLId"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element identifies the Id associated with a 'Uniform Resource Locator' (URL). </xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="SourceURL"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the 'Uniform Resource Locator' (URL) of the source from which the web page is accessed. </xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="SourceURLTitleName"
				type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element identifies the title associated with a web page.  Example: &quot;The Chubb Corporation&quot; is assoicated with  &quot;HTTP://WWW.CHUBB.COM&quot;</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="SourceButtonImageURL"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the 'Uniform Resource Locator' (URL) of the button image from which the web page is accessed. </xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="SourceSortOrderNumber"
				type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This value represents the order in which the Source Information is presented to the user.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="SourceCategoryTitleName"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element identifies the title associated with a category of  'Uniform Resource Locators' (URLs).  Example: &quot;Access Risk Management Tools&quot; .</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="SourceCategoryButtonImageURL" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the 'Uniform Resource Locator' (URL) of the category button image from which the web page is accessed. </xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="SourceCategorySortOrderNumber" type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element represents the order in which the Source Category Information is presented to the user.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="VisibilityIndicator"
				type="xsd:boolean">
				<xsd:annotation><xsd:documentation>This element specifies whether the SourceURLTitleName is visible to the user.</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>