<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://ei/core/line_of_business_information">
	<xsd:complexType name="LineOfBusinessInformation">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="LineOfBusinessCode"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the code for the line of business.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="LineOfBusinessAbbreviation"
				type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element contains the abbreviation for the line of business.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element maxOccurs="1" minOccurs="0"
				name="LineOfBusinessName" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the name of the line of business.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>
