<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://ei/core/location_occupancy_aggregationx2"
	xmlns:bons0="http://ei/core/location_occupancy_calculation"
	xmlns:bons2="http://ei/core/exposurex2"
	xmlns:bons3="http://ei/core/limitx3"
	xmlns:bons1="http://ei/core/premiumx7">
	<xsd:import schemaLocation="PremiumX7.xsd"
		namespace="http://ei/core/premiumx7">
	</xsd:import>
	<xsd:import schemaLocation="LimitX3.xsd"
		namespace="http://ei/core/limitx3">
	</xsd:import>
	<xsd:import schemaLocation="Exposurex2.xsd"
		namespace="http://ei/core/exposurex2">
	</xsd:import>

	<xsd:import
		namespace="http://ei/core/location_occupancy_calculation"
		schemaLocation="LocationOccupancyCalculation.xsd">
	</xsd:import>


	<xsd:complexType name="LocationOccupancyAggregation">
		<xsd:sequence>
			<xsd:element maxOccurs="unbounded" minOccurs="0"
				name="Exposure" type="bons2:Exposure">
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0"
				name="Limit" type="bons3:Limit">
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0"
				name="Premium" type="bons1:Premium">
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0"
				name="LocationOccupancyCalculation"
				type="bons0:LocationOccupancyCalculation">
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>