<?xml version="1.0" encoding="UTF-8"?><xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://ei/core/management_oriented_codes">
	<xsd:complexType name="ManagementOrientedCodes">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="DivisionCode" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>This element contains a code which identifies the responsible division in regards profit (LOSS); the first level of
management-oriented data elements. &lt;br /&gt;</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="DivisionDescription" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>This element&amp;nbsp;describes the responsible division in regards profit (LOSS); the first level of management-oriented data
elements. &lt;br /&gt;</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ManagementResponsibilityCode" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>&lt;p&gt;
    This element contains a business categories designated by P&amp;amp;C management for use in analysis of profit (LOSS)
    results; the second level of management oriented data elements.
&lt;/p&gt;</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ManagementResponsibilityDescription" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>&lt;p&gt;
    This element describes the&amp;nbsp;business categories designated by P&amp;amp;C management for use in analysis of profit
    (LOSS) results; the second level of management oriented data elements.
&lt;/p&gt;</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="MarketingResponsibilityCode" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>&lt;p&gt;
    This element contains a code which identifies the responsible marketing organization; it is the third level of
    management-oriented data elements.
&lt;/p&gt;</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="MarketingResponsibilityDescription" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>&lt;p&gt;
    This element describes the responsible marketing organization; it is the third level of management-oriented data
    elements.
&lt;/p&gt;</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ProfitabilityAnalysisCode" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>&lt;p&gt;
    This element contains a business categories designed by P&amp;amp;C management for use in analysis of profit (LOSS)
    results; the fourth level of management oriented data elements.
&lt;/p&gt;</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ProfitabilityAnalysisDescription" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>&lt;p&gt;
    This element descibes&amp;nbsp;the business categories designed by P&amp;amp;C management for use in analysis of profit (LOSS)
    results; the fourth level of management oriented data elements.
&lt;/p&gt;</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>