<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:bons0="http://ei/core/addressx1"
	targetNamespace="http://ei/core/medical_institution">
	<xsd:import namespace="http://ei/core/addressx1"
		schemaLocation="AddressX1.xsd">
	</xsd:import>
	<xsd:complexType name="MedicalInstitution">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="MedicalInstitutionName"
				type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element contains the name of a medical institution, which could be hospital , clinic or laboratory.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="Address"
				type="bons0:Address">
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>
