<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bons1="http://ei/core/medical_institution" targetNamespace="http://ei/core/medical_investigator">
    <xsd:import namespace="http://ei/core/medical_institution" schemaLocation="MedicalInstitution.xsd"/>
	<xsd:complexType name="MedicalInvestigator">
		<xsd:sequence>

			<xsd:element minOccurs="0" name="MedicalInstitution" type="bons1:MedicalInstitution">
			</xsd:element>
			<xsd:element minOccurs="0" name="InvestigatorName" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the name of an investigator.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="InvestigatorTitleName" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the title of the investigator.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PhoneNumber" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a person's phone number.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="FaxNumber" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a person's fax number.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="EmailAddress" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a person's e-mail address.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>
