<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ei/core/performerx1"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:bons0="http://ei/core/typed_address"
	xmlns:bons1="http://ei/core/phone_information"
	xmlns:bons2="http://ei/core/email_information">
	<xsd:import schemaLocation="EmailInformation.xsd"
		namespace="http://ei/core/email_information">
	</xsd:import>
	<xsd:import schemaLocation="PhoneInformation.xsd"
		namespace="http://ei/core/phone_information">
	</xsd:import>
	<xsd:import schemaLocation="TypedAddress.xsd"
		namespace="http://ei/core/typed_address">
	</xsd:import>
	<xsd:complexType name="Performer">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="TypedAddress"
				type="bons0:TypedAddress" maxOccurs="unbounded">
			</xsd:element>
			<xsd:element minOccurs="0" name="PhoneInformation"
				type="bons1:PhoneInformation" maxOccurs="unbounded">
			</xsd:element>

			<xsd:element minOccurs="0" name="EmailInformation"
				type="bons2:EmailInformation" maxOccurs="unbounded">
			</xsd:element>
			<xsd:element minOccurs="0" name="BusinessName"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains the name of a business.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="BusinessEntityIndicator"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element indicates if something is a business entity.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="GivenName"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains a person's first name.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="MiddleInitial"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains the first letter from a person's middle name.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="Surname"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains a person's last name.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="NameSuffix"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains the suffix that follows a person’s full name and provides additional information about the person. There are academic, honorary, professional, and social name suffixes.
</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PerformerRoleTypeCode"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains a code that identifies the role type of the performer.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PerformerRoleTypeName"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains a name that identifies the role type of the performer.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PerformerNumber"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains the number of the performer.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PerformerCode"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains a code used to identify a performer.</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>