<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ei/core/peril_information"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="PerilInformation">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="EnterprisePerilCode"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a code that identifies the Peril. 
The E1T01541Corporate Table contains valid values for this element in the "ENTRP_PRL_C" column.

</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="EnterprisePerilAbbreviation" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains an abbreviation that identifies the Peril. 
The E1T01541Corporate Table contains valid values for this element in the "ENTRP_PRL_AB" column.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="EnterprisePerilShortName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a shortened name that identifies the Peril. 
The E1T01541Corporate Table contains valid values for this element in the "ENTRP_PRL_SHRT_NA" column.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="EnterprisePerilMixedCaseShortName" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a shortened name that identifies the Peril. 
The E1T01541Corporate Table contains valid values for this element in the "ENTRP_PRL_MXCSH_NA" column.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="EnterprisePerilName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a name that identifies the Peril. 
The E1T01541Corporate Table contains valid values for this element in the "ENTRP_PRL_NA" column.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="EnterprisePerilMixedCaseName" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a name that identifies the Peril. 
The E1T01541Corporate Table contains valid values for this element in the "ENTRP_PRL_MXC_NA" column.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PerilTypeCode"
				type="xsd:string"><xsd:annotation><xsd:documentation>This code indentifies a major grouping of property perils such as Fire, EC, Eqke, or AOP.



</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PerilTypeName"
				type="xsd:string"><xsd:annotation><xsd:documentation>This contains the name of the major grouping of property perils such as Fire, Earthquake, and Wind and Hail.</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>