<?xml version="1.0" encoding="UTF-8"?><xsd:schema targetNamespace="http:/ei/core/policy_processing_note_set" xmlns:bons0="http://ei/core/policy_processing_note" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:import namespace="http://ei/core/policy_processing_note" schemaLocation="PolicyProcessingNote.xsd"/>
	<xsd:complexType name="PolicyProcessingNoteSet">
		<xsd:sequence>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="PolicyProcessingNote" type="bons0:PolicyProcessingNote">
			</xsd:element>
			<xsd:element minOccurs="0" name="ComponentName" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the name of a component such as application name or service name. </xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="BPRoleName" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the role of the business party.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>