<?xml version="1.0" encoding="UTF-8"?><xsd:schema targetNamespace="http://ei/core/policy_term_identifier" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="PolicyTermIdentifier">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="PolicyNumber" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element identifies an insurance contract.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="InceptionDate" type="xsd:date">
        <xsd:annotation>
          <xsd:documentation>This element specifies the inception date of a policy term. </xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ExpirationDate" type="xsd:date">
			</xsd:element>
			<xsd:element minOccurs="0" name="PolicyTypeCode" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>This element identifies the type of the insurance contract with a code.
The Corporate table E1T00221 contain the valid values for this element in the "POL_TY_C" column.
</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PolicyTypeSubCode" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>The element is used to divide Policy Type Code in order to provide more categories for some insurance contracts.  (This is also known as PolicySubTypeCode.)
The Corporate table E1T00221 contain the valid values for this element if the "POL_SUB_TY_C" column.
</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PolicyTypeEnglishAbbreviation" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>This element is the name assigned to a policy that represents the type of insurance contract. 
The Corporate table E1T00221 contain the valid values for this element if the "POL_TY_AB" column.
</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ControlNumber" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>This element is a unique identifier for each policy or submission.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="OfferingNumber" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>This element is a unique identifier for each policy or submission in the Client / WIP system.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="OfferingDB2Timestamp" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element is a unique identifier for each policy term in the Client/WIP System.
Values for this element are in a DB2 timestamp format: yyyy-mm-dd-hh.mm.ss.zzzzzz. </xsd:documentation>
        </xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>