<?xml version="1.0" encoding="UTF-8"?><xsd:schema targetNamespace="http://ei/core/policy_processing_data" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="PolicyProcessingData">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="PolicyProcessingDataTypeName" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the classification of the type of policy processing data.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PolicyProcessingDataName" type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element contains the name of an element needed during the processing of a policy.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PolicyProcessingDataValue" type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element contains the value of an element needed during the processing of a policy.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PolicyProcessingDataDate" type="xsd:date">
        <xsd:annotation>
          <xsd:documentation>This element contains a date related to the processing of the Policy.  It is used in conjunction with Policy Processing Data Name.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PolicyProcessingDataIndicator" type="xsd:boolean">
        <xsd:annotation>
          <xsd:documentation>This element contains an indicator related to the processing of the Policy.  It is used in conjunction with Policy Processing Data Name.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>