<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ei/core/policy_key_parameter"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="PolicyKeyParameter">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="PolicyKeyName"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element conatins the name of the type of Policy Key.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PolicyKeyValue"
				type="xsd:string" maxOccurs="unbounded">
				<xsd:annotation><xsd:documentation>This element contains an array of Policy Keys.</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>