<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://ei/core/product_policy_type_cross_reference"
	xmlns:bons0="http://ei/core/section_policy_type_cross_reference">
	<xsd:import schemaLocation="SectionPolicyTypeCrossReference.xsd"
		namespace="http://ei/core/section_policy_type_cross_reference">
	</xsd:import>
	<xsd:complexType name="ProductPolicyTypeCrossReference">
		<xsd:sequence>
			<xsd:element minOccurs="0"
				name="SectionPolicyTypeCrossReference"
				type="bons0:SectionPolicyTypeCrossReference"
				maxOccurs="unbounded">
			</xsd:element>
			<xsd:element minOccurs="0" name="SourceSystemProductCode"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains a product code as it is known by the source system.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PolicySymbolCode"
				type="xsd:string">
			</xsd:element>
			<xsd:element minOccurs="0" name="AccountTypeCode"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains the code identifying the type of account in Genius. Some valid values for
    this element include C (Custom), E(Express) and W(Westchester).
</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>