<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://ei/core/question_and_answerx1"
	xmlns:bons0="http://ei/core/customizationx1">
	<xsd:import namespace="http://ei/core/customizationx1"
		schemaLocation="CustomizationX1.xsd">
	</xsd:import>
	<xsd:complexType name="QuestionAndAnswer">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="QuestionTypeReferenceCode"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the code which indentifies the type of the question.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="QuestionId"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the number associated with the question.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="QuestionText"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a question.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="AnswerText"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the answer to the question.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="QuestionGroupNumber"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>&lt;br /&gt;
&lt;p&gt;
    This element contains&amp;nbsp;a number used to refer to a grouping of questions.
&lt;/p&gt;</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="QuestionGroupName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>&lt;br /&gt;
&lt;p&gt;
    This element contains a name used to refer to a grouping of questions.
&lt;/p&gt;</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0"
				name="Customization" type="bons0:Customization">
			</xsd:element>
			<xsd:element minOccurs="0" name="AnswerSequenceNumber"
				type="xsd:string"><xsd:annotation><xsd:documentation>&lt;br /&gt;
&lt;p&gt;
    This element is used when there can be multiple answers/lines to the same question.
&lt;/p&gt;</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="QuestionSectionNumber"
				type="xsd:string"><xsd:annotation><xsd:documentation>&lt;br /&gt;
&lt;p&gt;
    This element contains the section of the question, the same question can appear multiple times on the same form with
    different context.&amp;nbsp;&amp;nbsp; For example, you may need gather the Address of multiple business parties.
&lt;/p&gt;</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>