<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://ei/core/referral_zone">
	<xsd:complexType name="ReferralZone">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="ReferralZoneIndicator"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This elements indicates if a location resides within a referral zone.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="ReferralZoneTypeAbbrevation" type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains the type abbreviation for the referral zone.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ReferralZoneTypeName"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains the type name for the referral zone.</xsd:documentation></xsd:annotation>
			</xsd:element>			<xsd:element minOccurs="0" name="ReferralZoneName"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains the name of the referral zone.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ReferralZoneCode"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains the code of the referral zone.</xsd:documentation></xsd:annotation>
			</xsd:element>		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>
