<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://ei/core/routing_code_information">
	<xsd:complexType name="RoutingCodeInformation">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="RoutingIdCode"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the id for routing financial transactions.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="RoutingCodeTypeName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the type of Routing Id Code.  Some valid values include 'BIC', 'ABA' and 'CHIPS'.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>