<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
	targetNamespace="http://ei/core/special_arrangement_producer"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:bons2="http://ei/core/special_arrangement_fee"
	xmlns:bons0="http://ei/core/business_party_characteristic">
	<xsd:import schemaLocation="BusinessPartyCharacteristic.xsd"
		namespace="http://ei/core/business_party_characteristic">
	</xsd:import>
	<xsd:import schemaLocation="SpecialArrangementFee.xsd"
		namespace="http://ei/core/special_arrangement_fee">
	</xsd:import>

	<xsd:complexType name="SpecialArrangementProducer">
		<xsd:sequence>
			<xsd:element maxOccurs="unbounded" minOccurs="0"
				name="SpecialArrangementFee" type="bons2:SpecialArrangementFee">
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0"
				name="SpecialArrangementProducerCharacteristic"
				type="bons0:BusinessPartyCharacteristic">
			</xsd:element>
			<xsd:element minOccurs="0"
				name="SpecialArrangementProducerNumber" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element is a Chubb ID number for an agent or broker under a special arrangement.
This is also known as the Agent Number.
The AGTAGDA1 Corporate Table contains valid values for this element in the "AGT_N" column.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="SpecialArrangementProducerSubNumber" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element identifies a subdivision of business within an agent or broker under a special arrangement.
This also known as Sub Agent Number or Sub Producer Number.
The AGTAGDA1 Corporate Table contains valid values for this element in the "SUB_AGT_N" column.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="SpecialArrangementOriginalCurrencyCode" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element is a code for the original currency associated with the special arrangement prior to translation.  
The E1T00121 Corporate Table contains valid values for this element in the "ORIG_CUR_C" column. </xsd:documentation>
        </xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0"
				name="SpecialArrangementProducerDescription" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element is used to describe in more detail what that special arrangement producer is being used for when additional clarity is needed.  One possible usage is in CPI where they need to track below the line of business level.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="MessageSpecialArrangementProducerId" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains an Id assigned for the  lifetime of the message that will be used to identify the Special Arrangement Producer.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>