<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
	targetNamespace="http://ei/core/survey_evaluation_information"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="SurveyEvaluationInformation">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="SurveyEvaluationItemName"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element identifies the name of the item to be evaluated in a survey.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="SurveyEvaluationItemValue"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element identifies the value of the item to be evaluated in a survey.</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>