<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ei/core/survey_location"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:bons0="http://ei/core/standardized_addressx3">
	<xsd:import schemaLocation="StandardizedAddressX3.xsd"
		namespace="http://ei/core/standardized_addressx3">
	</xsd:import>
	<xsd:complexType name="SurveyLocation">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="SurveyAddress"
				type="bons0:StandardizedAddress">
				<xsd:annotation><xsd:documentation>The survey address is the address provided by the person requesting the survey.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="StandardizedAddress"
				type="bons0:StandardizedAddress">
			</xsd:element>
			<xsd:element minOccurs="0" name="SurveyLocationName"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains the name of the location to be surveyed</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="SurveySiteTypeCode"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains a code identifying the type of site to be surveyed.   Valid values  for this element can be found in application specific reference tables.
</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="LocationSICCode"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element identifies a major industry classification as determined by the US Federal Government. 
The first two characters of the SIC code are the Major Group.
The last two characters of the SIC code are the Industry Code.  
The E1T00331 Corporate Table contains valid values for the SIC Code(SIC_C), as well as columns for Major Group (SIC_MAJ_GRP_C) and Industry Code (SIC_INDST_C). 
The E1T00321 Corporate Table contains valid values for only the Major Group (SIC_MAJ_GRP).</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>