<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ei/core/taxing_jurisdictionx1"
	xmlns:bons0="http://ei/core/line_of_business_tax_ratex1"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:import namespace="http://ei/core/line_of_business_tax_ratex1"
		schemaLocation="LineOfBusinessTaxRateX1.xsd">
	</xsd:import>
	<xsd:complexType name="TaxingJurisdiction">
		<xsd:annotation>
      <xsd:documentation>This element contains the code for the Taxing Jurisidction, for the Taxing Jurisidction contained in the name element.</xsd:documentation>
    </xsd:annotation>
		<xsd:sequence>
			<xsd:element maxOccurs="unbounded" minOccurs="0"
				name="LineOfBusinessTaxRate" type="bons0:LineOfBusinessTaxRate">
			</xsd:element>
			<xsd:element minOccurs="0" name="TaxingJurisdictionTypeName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the name of the type of taxing jurisidiction.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="TaxingJurisdictionCode"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the code for the Taxing Jurisidiction, for the Taxing Jurisidiction contained in the name element</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="TaxingJurisdictionName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the name for the Taxing Jurisidction.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>


			<xsd:element minOccurs="0" name="TaxCode"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains a unique tax number for a geographic area.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="TaxingJurisdictionMinTaxAmount" type="xsd:decimal"><xsd:annotation><xsd:documentation>This element contains the minimum tax amount for a taxing jurisdiction.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="TaxRateAccuracyMatchCode"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element specifies the accuracy of the match.

The valid options for this element are:
E -  Exact match on street and address range
S  -  ‘close’ match, on street but not the address range
U  - (un-numbered) is a close match where the street matches but there is no address range info available
P  -  Approximate match.  The street cannot be found but ISO uses the center of the appropriate postal carrier route to assign data.
Z   - Zip centroid.  The street cannot be found. The center of the zip code is used to assign data.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="TaxingJurisdictionPercentInPostalCode" type="xsd:decimal"><xsd:annotation><xsd:documentation>This element contains the percent of the taxing jurisdiction that is within a particular postal code.
Valid values for this element are 0 to 1.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="TaxRateNotesText"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains additional information about the tax rate.</xsd:documentation></xsd:annotation>
			</xsd:element>



		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>