<?xml version="1.0" encoding="UTF-8"?><xsd:schema targetNamespace="http://ei/core/taxx2" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="Tax">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="TaxTypeReferenceCode" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element indentifies the type of tax (federal, state, ect.)

</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="TaxName" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a name that identifies a specific tax type.  </xsd:documentation>
        </xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0" name="TaxPercent" type="xsd:decimal">
				<xsd:annotation>
          <xsd:documentation>This element contains the percent of the tax to be paid.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="TaxAmount" type="xsd:decimal">
				<xsd:annotation>
          <xsd:documentation>This element contains the amount of tax to be paid.
</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="TaxCurrencyCode" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a code which indentifies the currency of the tax amount.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="TaxRate" type="xsd:decimal">
        <xsd:annotation>
          <xsd:documentation>This element contains the rate that will be applied to determine the Tax Amount.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PostalStateAbbreviation" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>This element is the two character US Postal State Abbreviation. 
The E1T00111 Corporate Table contains valid values for this element in the "PSTL_ST_AB" column. 
				</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>