<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
	targetNamespace="http://ei/core/text_analytics_concept_term_result"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="TextAnalyticsConceptTermResult">
		<xsd:sequence>
			<xsd:element minOccurs="0"
				name="TextAnalyticsConceptTermTypeName" type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element contains the name of the type of concept term.</xsd:documentation></xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0"
				name="TextAnalyticsConceptTermText" type="xsd:string"><xsd:annotation><xsd:documentation>This element element contains the text that applies to this concept term.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="TextAnalyticsConceptTermResultIndicator" type="xsd:boolean"><xsd:annotation><xsd:documentation>This element contains the result of a text analytics concept term that has been run on a text object.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="TextAnalyticsConceptTermResultValue" type="xsd:string"><xsd:annotation><xsd:documentation>This element contains data related to the concept term that was found in the text during the analysis. </xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="TextAnalyticsConceptTermResultDescription"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains describes the data related to the concept term that was found in the text during the analysis. </xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>