openapi: 3.0.3
info:
  title: loc-service29
  version: 0.1.0
paths:
  /loc/GetLocationList3X1B:
    post:
      operationId: GetLocationList3X1B
      requestBody:
        required: true
        content:
          application/xml:
            schema:
              type: string
      responses:
        '200':
          description: OK
          content:
            application/xml:
              schema:
                type: string
  /loc/GetStateOrProvince:
    post:
      operationId: GetStateOrProvince
      requestBody:
        required: true
        content:
          application/xml:
            schema:
              type: string
      responses:
        '200':
          description: OK
          content:
            application/xml:
              schema:
                type: string
  /loc/GetCountry:
    post:
      operationId: GetCountry
      requestBody:
        required: true
        content:
          application/xml:
            schema:
              type: string
      responses:
        '200':
          description: OK
          content:
            application/xml:
              schema:
                type: string
  /loc/GetLocationList3X1M:
    post:
      operationId: GetLocationList3X1M
      requestBody:
        required: true
        content:
          application/xml:
            schema:
              type: string
      responses:
        '200':
          description: OK
          content:
            application/xml:
              schema:
                type: string
  /loc/GetLocationWithTaxingJurisdictions3X1B:
    post:
      operationId: GetLocationWithTaxingJurisdictions3X1B
      requestBody:
        required: true
        content:
          application/xml:
            schema:
              type: string
      responses:
        '200':
          description: OK
          content:
            application/xml:
              schema:
                type: string
  /loc/GetLocationWithTaxingJurisdictions3X1M:
    post:
      operationId: GetLocationWithTaxingJurisdictions3X1M
      requestBody:
        required: true
        content:
          application/xml:
            schema:
              type: string
      responses:
        '200':
          description: OK
          content:
            application/xml:
              schema:
                type: string
