spring:
  application:
    name: mock-services

server:
  port: 8091

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level [%X{correlationId}] %logger{36} - %msg%n"
