openapi: 3.0.3
info:
  title: loc-service62
  version: 0.1.0
paths:
  /loc/GetLocation3X2B:
    post:
      operationId: GetLocation3X2B
      requestBody:
        required: true
        content:
          application/xml:
            schema:
              type: string
      responses:
        '200':
          description: OK
          content:
            application/xml:
              schema:
                type: string
  /loc/StandardizeUSAddress2X2:
    post:
      operationId: StandardizeUSAddress2X2
      requestBody:
        required: true
        content:
          application/xml:
            schema:
              type: string
      responses:
        '200':
          description: OK
          content:
            application/xml:
              schema:
                type: string
  /loc/StandardizeOSUSAddress2X2:
    post:
      operationId: StandardizeOSUSAddress2X2
      requestBody:
        required: true
        content:
          application/xml:
            schema:
              type: string
      responses:
        '200':
          description: OK
          content:
            application/xml:
              schema:
                type: string
  /loc/GetUKFloodInformation:
    post:
      operationId: GetUKFloodInformation
      requestBody:
        required: true
        content:
          application/xml:
            schema:
              type: string
      responses:
        '200':
          description: OK
          content:
            application/xml:
              schema:
                type: string
