package com.ei.camel.mappings;

import org.mapstruct.Mapper;

@Mapper
public interface LOC3X1GetLocationWithTaxingJurisdictionsRequestMapMapper {
    GetLocationWithTaxingJurisdictionsTypes.GetLocationWithTaxingJurisdictions3X1BRequestMsg map(GetLocationWithTaxingJurisdictionsTypes.GetLocationWithTaxingJurisdictionsRequestMsg source);
}
