<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:Port_0="http://ei/location/location_retrieval_loc3x3" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://ei/location/location_retrieval_loc3x3_http" name="LocationRetrievalLOC3X3Http" targetNamespace="http://ei/location/location_retrieval_loc3x3_http">
  <wsdl:import location="LocationRetrievalLOC3X3.wsdl" namespace="http://ei/location/location_retrieval_loc3x3"/>
  <wsdl:binding name="LocationRetrievalLOC3X3HttpBinding" type="Port_0:LocationRetrievalLOC3X3">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="GetLocation">
      <soap:operation soapAction="GetLocation"/>
      <wsdl:input name="GetLocationRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="GetLocationResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="SimpleFaultReply">
        <soap:fault name="SimpleFaultReply" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="GetLocationList">
      <soap:operation soapAction="GetLocationList"/>
      <wsdl:input name="GetLocationListRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="GetLocationListResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="SimpleFaultReply">
        <soap:fault name="SimpleFaultReply" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="LocationRetrievalLOC3X3HttpService">
    <wsdl:port binding="this:LocationRetrievalLOC3X3HttpBinding" name="LocationRetrievalLOC3X3HTTP_LocationRetrievalLOC3X3HttpPort">
      <soap:address location="http://EILOCRETRLOC3X3-ut/LocationServicesWeb/sca/LocationRetrievalLOC3X3Http"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
