<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
	targetNamespace="http://ei/core/assigned_resource_id_by_role"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="AssignedResourceIdByRole">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="CPNumber"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element is the number assigned to the contract partcipant.   A contract partcipant may be, but is not limited to, an insured, a prospective insured, a risk manager, 
an additional insured, or a Chubb resource.
</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="CPRoleCode"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element identifies the function or position a specific contract partcipant may play on a policy offering and/or service offering.
The E1T00771 Corporate Table contains valid values for this element in the &quot;CNTRCT_PRTC_ROL_C&quot; column. 
</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="CPRoleName"
				type="xsd:string">
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>