<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ei/core/billing_activity"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="BillingActivity">
		<xsd:annotation>
      <xsd:documentation>Billing Activities include Policy Admin System Premium Transactions (Newline, Renewal, and Endorsement, etc.) and Billing Account events.  Billing events examples are invoice sent and partial payment received. </xsd:documentation>
    </xsd:annotation>
		<xsd:sequence>
			<xsd:element minOccurs="0"
				name="BillingActivitySequenceNumber" type="xsd:integer">
				<xsd:annotation>
          <xsd:documentation>This element is used to order the billing activities.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="BillingActivityDate"
				type="xsd:date">
				<xsd:annotation>
          <xsd:documentation>This element contains the date of the billing activity.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="BillingActivityAmount"
				type="xsd:decimal">
				<xsd:annotation>
          <xsd:documentation>This element contains the amount of the billing activity.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="BillingActivityDescription"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the description of the billing activity.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PolicyNumber"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element identifies an insurance contract.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="BillingActivityPolicyDate"
				type="xsd:date">
				<xsd:annotation>
          <xsd:documentation>This element contains a the policy date most relevant to the current billing activity, which can the policy effective date, policy expiration date, or when no date applies contains placeholder date of 12/31/9999.  For example if it’s a new line for 1/1/15 to 1/1/16 this will contain the policy effective date 1/1/15. For policy transfer it contains the effective date.  For policy resume this will contain 12/31/9999</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="BillingActivityCommentsText" type="xsd:string">
				<xsd:annotation><xsd:documentation>Contains additional freeform text information about the BillingActivityDescription.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="LineOfBusinessName"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains the name of the line of business.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PolicyTypeCode"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element identifies the type of insurance contract with a code. The Corporate table E1T00221 contain the valid values
for this element in the &quot;POL_TY_C&quot; column.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PolicyTypeSubCode"
				type="xsd:string"><xsd:annotation><xsd:documentation>The element is used to divide Policy Type Code in order to provide more categories for some insurance contracts. (This is
also known as PolicySubTypeCode.) The Corporate table E1T00221 contain the valid values for this element if the
&quot;POL_SUB_TY_C&quot; column.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="BillPaymentIdentifier"
				type="xsd:string"><xsd:annotation><xsd:documentation>This identifies the unique instance of the customer payment. It could be related to 1 or more Billing Activities.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ContractNumber"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element identifies an&amp;nbsp;&amp;nbsp;insurance contract.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ControlNumber"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element is a unique identifier for each policy or submission</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>