<?xml version="1.0" encoding="UTF-8"?><xsd:schema targetNamespace="http://ei/core/bill_payor" xmlns:bons0="http://ei/core/business_partyx1" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:import namespace="http://ei/core/business_partyx1" schemaLocation="../Schemas/BusinessPartyX1.xsd">
	</xsd:import>
	<xsd:complexType name="BillPayor">
		<xsd:annotation>
      <xsd:documentation>The Bill Payor is the person responsible for paying the Bill for the Account.  The Bill Payor can be the Insured, Mortgagee, or Payroll(Employee).</xsd:documentation>
    </xsd:annotation>
		<xsd:complexContent>
			<xsd:extension base="bons0:BusinessParty">


				<xsd:sequence>
					<xsd:element minOccurs="0" name="BillToName" type="xsd:string">
						<xsd:annotation>
              <xsd:documentation>This element contains the name of the individual or organization to whom the bill is sent.</xsd:documentation>
            </xsd:annotation>
					</xsd:element>
					<xsd:element minOccurs="0" name="BillPayorTypeCode" type="xsd:string">
            <xsd:annotation>
              <xsd:documentation>This element contains a code that identifies the type of the bill payor.
Valid values include:  'I' - Insured, 'M' - Mortgagee, and 'P' - Payroll.
</xsd:documentation>
            </xsd:annotation>
					</xsd:element>
					<xsd:element minOccurs="0" name="BillPayorTypeName" type="xsd:string">
						<xsd:annotation>
              <xsd:documentation>This element contains the type of the Bill Payor.   
Valid values include:  Insured, Mortgagee, and Payroll.</xsd:documentation>
            </xsd:annotation>
					</xsd:element>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:schema>