<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
	targetNamespace="http://ei/core/business_event_informationx1"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:bons0="http://ei/core/business_event_detail"
	xmlns:bons1="http://ei/core/business_event_level_information">
	<xsd:import schemaLocation="BusinessEventLevelInformation.xsd"
		namespace="http://ei/core/business_event_level_information">
	</xsd:import>
	<xsd:import schemaLocation="BusinessEventDetail.xsd"
		namespace="http://ei/core/business_event_detail">
	</xsd:import>

	<xsd:complexType name="BusinessEventInformation">
		<xsd:sequence>
			<xsd:element minOccurs="0"
				name="BusinessEventLevelInformation"
				type="bons1:BusinessEventLevelInformation" maxOccurs="unbounded">
			</xsd:element>
			<xsd:element minOccurs="0" name="BusinessEventDetail"
				type="bons0:BusinessEventDetail" maxOccurs="unbounded">
			</xsd:element>

			<xsd:element minOccurs="0" name="BusinessEventName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the name assigned to the business event.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="BusinessEventId"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains a unique identifier assigned to the busienss event.</xsd:documentation></xsd:annotation>
			</xsd:element>


			<xsd:element minOccurs="0" name="BusinessEventPriorityName"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains the priority of the business event.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="BusinessEventTimestamp"
				type="xsd:dateTime">
				<xsd:annotation><xsd:documentation>This element contains the date/time that the business event occured. 
</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>