<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
	targetNamespace="http://ei/core/coverage_category_information"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="CoverageCategoryInformation">
		<xsd:sequence>
			<xsd:element minOccurs="0"
				name="SourceSystemCoverageCategoryCode" type="xsd:string">
				<xsd:annotation>
          
        
        <xsd:documentation>This element contains the code for the coverage category as it is known by the source system.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="SourceSystemCoverageCategoryAbbreviation" type="xsd:string">
				<xsd:annotation>
          
        
        
        <xsd:documentation>This element contains the abbreviation for the coverage category as it is known by the source system.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element maxOccurs="1" minOccurs="0"
				name="SourceSystemCoverageCategoryName" type="xsd:string">
				<xsd:annotation>
          
        
        <xsd:documentation>This element contains the name of the coverage category as it is known by the source system.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="SourceSystemCoverageCategoryMixedCaseShortName"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains the short name that identifies a coverage category in mixed case format as it is known by the source system.</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>