<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http:/core/custom_business_data_group"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:bons0="http://ei/core/custom_business_data">
	<xsd:import schemaLocation="CustomBusinessData.xsd"
		namespace="http://ei/core/custom_business_data">
	</xsd:import>
	<xsd:complexType name="CustomBusinessDataGroup">
		<xsd:annotation><xsd:documentation>This object is used to give a context and group together many abstract elements that are within custom business data.</xsd:documentation></xsd:annotation>
		<xsd:sequence>
			<xsd:element minOccurs="0" name="CustomBusinessData"
				type="bons0:CustomBusinessData" maxOccurs="unbounded">
				<xsd:annotation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="CustomBusinessDataGroupName" type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains the name of a group of custom business data.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="CustomBusinessDataGroupNumber" type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains a number assigned to a business data group.</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>