<?xml version="1.0" encoding="UTF-8"?><xsd:schema targetNamespace="http://ei/core/deductiblex2" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="Deductible">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="DeductibleTypeReferenceCode" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a code that identifies a specific deductible type.

</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="DeductibleName" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the name that identifies a specific deductible type.  </xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="DeductibleAmount" type="xsd:decimal">
				<xsd:annotation>
          <xsd:documentation>This element contains the amount of a loss for which the insured agrees to assume liability.  </xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="DeductibleCurrencyCode" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a code which indentifies the currency of the deductible amount.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="DeductibleAmountTypeName" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element describes the type of data contained in the deductible amount.
Valid values for this element include Currency, Distance, Time, and Quantity.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="UnitOfMeasure" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element specifies the measure for the Amount provided for Distance, Time, and Quantity Amounts. 
Some valid values for this element would include day, weeks, months.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="DeductibleCurrencyExchangeRate" type="xsd:decimal">
				<xsd:annotation>
          <xsd:documentation>This element is used in a calculation to convert deductible amounts from one currency to another currency.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="DeductibleRate" type="xsd:decimal">
				<xsd:annotation>
          <xsd:documentation>This element contains the Rate that will be applied to determine the Deductible Amount.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="DeductiblePercent" type="xsd:decimal">
				<xsd:annotation>
          <xsd:documentation>This element contains a percent of the total deductible.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>

		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>