<?xml version="1.0" encoding="UTF-8"?><xsd:schema targetNamespace="http://ei/core/driver_violation" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="DriverViolation">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="DriverViolationSequenceNumber" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the sequence number of the driver violation.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="MVRConvictionDate" type="xsd:date">
				<xsd:annotation>
          <xsd:documentation>This element contains the date of an Motor Vehicle Conviction. </xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ViolationDate" type="xsd:date">
				<xsd:annotation>
          <xsd:documentation>This element contains the violation date.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ViolationDescription" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a description of the violation. </xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ViolationSeverityTypeName" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the severity of the violation.
Valid values include major and minor.
</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ViolationCategoryTypeName" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the a category of the violation.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ViolationExperiencePeriodIndicator" type="xsd:boolean">
				<xsd:annotation>
          <xsd:documentation>This element indicates if the violation occured within the period being looked at.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ViolationDataSourceName" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the source of the violation data.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="DrivingRecordGIN" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>This element contains an unique driving record number assigned by Chubb, to the driving record data is received from Choicepoint.         </xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="StandardViolationTypeCode" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>This element  identifies the standard code generated by the vendor based on state specific terminology and codes used by different jurisdictions.  This code is intended to facilitate automatic processing of state supplied information).</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ViolationOrConvictionCode" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>This element contains a code to convey whether a violation is convicted.
Valid values for this element include: 'C'-Conviction or 'V' - Violation.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>