<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ei/core/external_vendor_system"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="ExternalVendorSystem">
		<xsd:annotation><xsd:documentation>This is the name of the vendor system currently installed at the producer's location, or that provides an input file to Chubb's Producers or other Chubb processes.</xsd:documentation></xsd:annotation>
		<xsd:sequence>
			<xsd:element minOccurs="0" name="VendorName"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains the name of a vendor (individual or legal entity) who may provide service to the organization, to a client of the organization or to a claimant.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="VendorSystemName"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains the name of the vendor system currently installed at the producer's location, or that provides an input file to Chubb's Producers or other Chubb processes.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="VendorSystemVersionName"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains the version number for a vendor system.  For example 9.1.2.</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>