<?xml version="1.0" encoding="UTF-8"?><xsd:schema targetNamespace="http://ei/core/family_office" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="FamilyOffice">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="FamilyOfficeCode" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>This element contains the code that identifies the family office as a legal entity.
</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="FamilyOfficeLegalName" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>This element contains the name of the family office as a legal entity.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="FamilyOfficeManagedIndicator" type="xsd:boolean">
        <xsd:annotation>
          <xsd:documentation>This element indicates a Family Offices is managing the Policy on behalf of the Insured.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>