<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ei/core/household"
	xmlns:Q1="http://ei/core/addressx4"
	xmlns:bons2="http://ei/core/customer_segment"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:import schemaLocation="AddressX4.xsd"
		namespace="http://ei/core/addressx4">
	</xsd:import>
	<xsd:import namespace="http://ei/core/customer_segment"
		schemaLocation="CustomerSegment.xsd" />
	<xsd:complexType name="Household">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="CustomerSegment"
				type="bons2:CustomerSegment">
			</xsd:element>
			<xsd:element minOccurs="0" name="HouseholdAddress"
				type="Q1:Address">
			</xsd:element>
			<xsd:element minOccurs="0" name="HouseholdDurableKey"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element conatins an unique identifier assigned to an instance of a Chubb household for its entire lifetime.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0" name="HouseholdName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the name which refers to the household as a whole.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0"
				name="HouseholdFirstChubbAssociationYear" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the year that the household first held a policy with Chubb.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>

		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>