<?xml version="1.0" encoding="UTF-8"?><xsd:schema targetNamespace="http://ei/core/input_parameter" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="InputParameter">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="InputParameterName" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>This element contains the name of an input parameter.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="InputParameterValue" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>This element contains the value of an input parameter element.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>