<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
	targetNamespace="http://ei/core/location_adjacency_calculation"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="LocationAdjacencyCalculation">
		<xsd:annotation></xsd:annotation>
		<xsd:sequence>
			<xsd:element minOccurs="0" name="LocationAdjacencyCalcName"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains the name of the location adjacency calculation.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="LocationAdjacencyCalcAmount" type="xsd:decimal"><xsd:annotation><xsd:documentation>This element contains a location adjacency calculation.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="LocationAdjacencyCalcValue"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains a location adjacency calculation.</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>