<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
	targetNamespace="http://ei/core/location_occupancy_aggregation"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:bons1="http://ei/core/limitx2"
	xmlns:bons2="http://ei/core/premiumx5"
	xmlns:bons3="http://ei/core/exposurex1"
	xmlns:bons0="http://ei/core/location_occupancy_calculation">
	<xsd:import schemaLocation="Exposurex1.xsd"
		namespace="http://ei/core/exposurex1">
	</xsd:import>
	<xsd:import schemaLocation="LocationOccupancyCalculation.xsd"
		namespace="http://ei/core/location_occupancy_calculation">
	</xsd:import>

	<xsd:import schemaLocation="PremiumX5.xsd"
		namespace="http://ei/core/premiumx5">
	</xsd:import>
	<xsd:import schemaLocation="LimitX2.xsd"
		namespace="http://ei/core/limitx2">
	</xsd:import>

	<xsd:complexType name="LocationOccupancyAggregation">
		<xsd:sequence>
			<xsd:element minOccurs="0" maxOccurs="unbounded"
				name="Exposure" type="bons3:Exposure">
			</xsd:element>
			<xsd:element minOccurs="0" maxOccurs="unbounded"
				name="Limit" type="bons1:Limit">
			</xsd:element>
			<xsd:element minOccurs="0" name="Premium"
				type="bons2:Premium" maxOccurs="unbounded">
			</xsd:element>
			<xsd:element minOccurs="0"
				name="LocationOccupancyCalculation"
				type="bons0:LocationOccupancyCalculation" maxOccurs="unbounded">
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>