<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:bons3="http://ei/core/message_logging_information"
	targetNamespace="http://ei/core/message_logging_information">

	<xsd:complexType name="MessageLoggingInformation">
		<xsd:sequence>



			<xsd:element minOccurs="0" name="MessageGroupId"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains a unique id that allows the parts of related messages to be grouped together, such as the request and reply.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="MessageId"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains a unique id to identify a message.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="MessageSenderGatewayName"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains the name of the gateway that sent the message.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="MessageTypeName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element indetifies the type of the message, such as request/reply.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="MessageSubTypeName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element allows the for a subset of types within one message type.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ProcessClassificationName"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element allows the source of the data to be classified so a specific action(process) can be taken based on whay system and/or CCM is supplying the data.

</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="SystemId"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element identifies internal/external sources of information.
This is also known as the System Source Code. 
The Corporate table E1T00871 contains the valid values for this element in the &quot;SYS_SRC_C&quot;  column.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="UserId"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element is used to sign on to an application.  
This is also known as RACFId.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="CertificateSubjectDN"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element is one field in the contents of a digital certificate, the Subject Distinguished Name.  It identifies the person or entity.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ServiceInterfaceName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element identifies the name of the service interface (e.g. ProducerValidationPRD1X2).</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="OperationName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the name of the operation.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="URL" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a Uniform Resource Location, which is a simple and extensible means for locating a resource.
A URL consists of a schema: &lt;scheme&gt;:&lt;scheme-specific-part&gt;.  The list of valid schemes is registered with IANA (Internet Assigned Numbers Authority: http://www.iana.org http://www.iana.org)
Some valid schemes include ftp, file, and http. </xsd:documentation>
        </xsd:annotation>
			</xsd:element>





			<xsd:element minOccurs="0" name="DeviceName"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains the name of a device.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="EnvironmentName"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element represents the name of the environment where a system executes.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PlatformName"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains the name of the platform.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PlatformVersionNumber"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element identifies the version of the platform.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="TransportProtocol"
				type="xsd:string"><xsd:annotation><xsd:documentation>This elements desribes the protocol used, such as MQ, HTTP, HTTPS, JMS.
</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="HTTPStatusCode"
				type="xsd:integer">
				<xsd:annotation><xsd:documentation>This element contains a result code that describes the status of the HTTP request.   This is a 3-digit integer result code.  The first digit of the Status-Code defines the class of response. The last two digits do not have any categorization role. There are 5 values for the first digit: 
      - 1xx: Informational - Request received, continuing process.
      - 2xx: Success - The action was successfully received,  understood, and accepted.
      - 3xx: Redirection - Further action must be taken in order to complete the request.
      - 4xx: Client Error - The request contains bad syntax or cannot be fulfilled.
      - 5xx: Server Error - The server failed to fulfill an apparently valid request.

</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="AuthenticationTypeName"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains the name of the type of authentication used.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="RequestorAuthorizedStatusCode" type="xsd:string"><xsd:annotation><xsd:documentation>This element contains a code that describes the authorization status of the requesting user or system,</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="FailureTypeName"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains the name of what failed to complete successfully.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="FailureDescription"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element describes why something failed to complete successfully.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="DataPowerBackendFailureIndicator" type="xsd:boolean">
				<xsd:annotation><xsd:documentation>This element indicates if a back-end  failure occured in DataPower.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="NumberOfTotalDocuments"
				type="xsd:integer"><xsd:annotation><xsd:documentation>This element contains the total number of documents.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="LogTimestamp"
				type="xsd:dateTime">
				<xsd:annotation><xsd:documentation>This element contains the timestamp for logging.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="MessageTimestamp"
				type="xsd:dateTime">
				<xsd:annotation>
          <xsd:documentation>This element contains the timestamp of the message.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="MessageHeaderXML">
				<xsd:annotation>
          <xsd:documentation>This contains the data that is in the message header.</xsd:documentation>
        </xsd:annotation>
				<xsd:complexType>
					<xsd:sequence>
						<xsd:any minOccurs="0" namespace="##other"
							processContents="lax" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element minOccurs="0" name="MessageContextXML">
				<xsd:annotation><xsd:documentation>This contains additional data that was is the message and it not contained in the header or body of the message.</xsd:documentation></xsd:annotation>
				<xsd:complexType>
					<xsd:sequence>
						<xsd:any minOccurs="0" namespace="##other"
							processContents="lax" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element minOccurs="0" name="MessageBodyXML">
				<xsd:annotation>
          <xsd:documentation>This contains the data that was in the message body.</xsd:documentation>
        </xsd:annotation>
				<xsd:complexType>
					<xsd:sequence>
						<xsd:any minOccurs="0" namespace="##other"
							processContents="lax" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element minOccurs="0" name="ErrorXML">
				<xsd:annotation>
          <xsd:documentation>This contains the error information.</xsd:documentation>
        </xsd:annotation>
				<xsd:complexType>
					<xsd:sequence>
						<xsd:any minOccurs="0" namespace="##other"
							processContents="lax" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>
