<?xml version="1.0" encoding="UTF-8"?><xsd:schema targetNamespace="http://ei/core/modifier" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="Modifier">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="ModifierTypeReferenceCode" type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element contains a code that identifies a specific modifiier.
</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ModifierName" type="xsd:string">
				<xsd:annotation>
          
        
        <xsd:documentation>This element contains the name to indentify a specific modifier.

</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ModifierCategoryName" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element is used to assign a category grouping to modifiers.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ModFactorValue" type="xsd:decimal">
				<xsd:annotation>
          <xsd:documentation>This element is a component used in a calculation to determine the value of the premium.

</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="MinimumModFactorValue" type="xsd:decimal">
				<xsd:annotation>
          <xsd:documentation>This element contains the minimum modification factor that can be applied to premium.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="MaximumModFactorValue" type="xsd:decimal">
				<xsd:annotation>
          <xsd:documentation>This element contains the maximun modification factor that can be applied to premium.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ParentTypeModifierReferenceCode" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the code for the parent modifier.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ParentModifierName" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the name of the parent modifier.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="GroupModifierIndicator" type="xsd:boolean">
				<xsd:annotation>
          <xsd:documentation>This element indicates if this modifier is the parent for a group of modifiers.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ModifierAdjustableIndicator" type="xsd:boolean">
				<xsd:annotation>
          <xsd:documentation>This element indicates if the value for this modifier can be adjusted.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ModifierSelectionClassName" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contain the name of a class that a particular modifier value may belongs.   Valid values may include average, above average, or good to excellent.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ModifierAmount" type="xsd:decimal">
				<xsd:annotation>
          <xsd:documentation>This element contains an amount associated with a modifier.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ModifierPercent" type="xsd:decimal">
				<xsd:annotation>
          <xsd:documentation>This element contains a percent of the total modifier amount.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>