<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://ei/core/native_language_information">
	<xsd:complexType name="NativeLanguageInformation">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="NativeLanguageName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the native language of the entity.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="NativeLanguageCharacterSetName" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the character set of the native language. Some valid values include 'Cyrillic' and 'Greek'.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="LatinLanguageName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the Latin character version of the name.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="NativeLanguageTypeName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the type of NativeLanguageName. Some valid values include 'Primary' and 'Alias'.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>