<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ei/core/payment_method"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="PaymentMethod">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="PaymentMethodCategoryName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the name of the payment method categories, such as Pay Now, Chubb Autopay, Credit/Debit Autopay, and Checkfree services.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PaymentMethodCode"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the code of the payment method, such as AutoPay, Credit, Debit, E-Check, and checkfree.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0" name="PaymentMethodStatusName"
				type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element indicates if this Billing Account is enrolled or eligible for this payment method.   Valid values include 'eligible' or 'enrolled'.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PaymentPreferenceCode"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element indicates the preference on the type of payment.  
The valid values may differ by billing system.   The valid values for Direct Bill are 'BAL' - Entire Balance or 'MIN' - Minimum Due.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PaymentVendorRoutingCode"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the vendor routing code for the payment method.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>