<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://ei/core/QuestionAndAnswer">
	<xsd:complexType name="QuestionAndAnswer">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="QuestionTypeReferenceCode"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains the code which indentifies the type of the question.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="QuestionId"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains the number associated with the question.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="QuestionText"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains a question.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="AnswerText"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains the answer to the question.</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>
