<?xml version="1.0" encoding="UTF-8"?><xsd:schema targetNamespace="http://ei/core/risk_rating_group" xmlns:bons1="http://ei/core/risk_rating_parameter" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:import namespace="http://ei/core/risk_rating_parameter" schemaLocation="RiskRatingParameter.xsd"/>
	<xsd:complexType name="RiskRatingGroup">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="RiskRatingGroupName" type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element contains the name of a group of data used for risk and/or rating.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="RiskRatingGroupNumber" type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element contains the number of a group of data used for risk and/or rating.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="RiskRatingParameter" type="bons1:RiskRatingParameter">
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>