<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://ei/core/service_information">
	<xsd:complexType name="ServiceInformation">
		<xsd:annotation></xsd:annotation>
		<xsd:sequence>
			<xsd:element minOccurs="0" name="ServiceInterfaceName"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element identifies the name of the service interface (e.g. ProducerValidationPRD1X2).</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="TransportProtocol"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element describes the mechanism that is used to invoke services. It is used to describe how an application 
calls a service and how the data is shared.  Some valid values are MQ, HTTP, JMS.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="EnvironmentName"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element represents the name of the environment where a system executes. </xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ServiceVersionNumber"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element identifies a particular verson of the service (e.g. 2.1 but could be more complex to include TestingIMEX)</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>
