<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
	targetNamespace="http://ei/core/survey_recommendation_response"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:bons2="http://ei/core/survey_contactx1"
	xmlns:bons0="http://ei/core/document_set"
	xmlns:bons1="http://ei/core/customizationx2">
	<xsd:import schemaLocation="CustomizationX2.xsd"
		namespace="http://ei/core/customizationx2">
	</xsd:import>
	<xsd:import schemaLocation="DocumentSet.xsd"
		namespace="http://ei/core/document_set">
	</xsd:import>
	<xsd:import schemaLocation="SurveyContactX1.xsd"
		namespace="http://ei/core/survey_contactx1">
	</xsd:import>


	<xsd:complexType name="SurveyRecommendationResponse">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="SurveyContact"
				type="bons2:SurveyContact" maxOccurs="unbounded">
			</xsd:element>
			<xsd:element minOccurs="0" name="DocumentSet"
				type="bons0:DocumentSet" maxOccurs="unbounded">
			</xsd:element>

			<xsd:element minOccurs="0"
				name="SurveyRecommendResponseNumber" type="xsd:integer"><xsd:annotation><xsd:documentation>This element contains the number that identifies the response to the survey recommendation.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="SurveyRecommendResponseText" type="xsd:string"><xsd:annotation><xsd:documentation>This element contains the response for the recommendation that is entered by the client.</xsd:documentation></xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0"
				name="SurveyRecommendResponseDate" type="xsd:date">
				<xsd:annotation><xsd:documentation>This element contains the date the response to the recommendation was entered by the client.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="SurveyRecommendTargetClientCompletionDate" type="xsd:date"><xsd:annotation><xsd:documentation>This element contains the date the client expects to complete the recommendation.</xsd:documentation></xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0"
				name="SurveyRecommendResponseDiaryDate" type="xsd:date"><xsd:annotation><xsd:documentation>This element is an internal date used by the Risk Engineer and Underwriter to know when follow up with the Chubb client on a recommendation response.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="SurveyRecommendClientCompletedDate" type="xsd:date"><xsd:annotation><xsd:documentation>This element contains the date the survey recommendation was reported as closed by the Chubb client.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="SurveyRecommendResponseUniqueId" type="xsd:string">
				<xsd:annotation><xsd:documentation>String representation of SurveyRecommendResponseNumber</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="Customization"
				type="bons1:Customization" maxOccurs="unbounded">
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>