<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ei/core/vehicle_registrantx1"
	xmlns:bons1="http://ei/core/business_party_characteristic"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:bons0="http://ei/core/typed_addressx3">
	<xsd:import schemaLocation="TypedAddressX3.xsd"
		namespace="http://ei/core/typed_addressx3">
	</xsd:import>
	<xsd:import namespace="http://ei/core/business_party_characteristic"
		schemaLocation="BusinessPartyCharacteristic.xsd">
	</xsd:import>
	<xsd:complexType name="VehicleRegistrant">
		<xsd:annotation>
      <xsd:documentation>This element contains the state or province where the vehicle registrant’s driver license was issued.</xsd:documentation>
    </xsd:annotation>
		<xsd:sequence>

			<xsd:element minOccurs="0"
				name="VehicleRegistrantSequenceNumber" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the sequence number of the vehicle registrant.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="VehicleRegistrantTypeCode"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a code that identifies the type of registrant.
Valid options for this element are:   '1'  - Driver, '2' - Non Driver, '3 - Corporation, '4' - Trust,  or '5' -  Living Trust/Trustee, or '6' Living Trust/Settler.
</xsd:documentation>
        </xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0" name="VehicleRegistrantGivenName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the vehicle registrant's first name.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="VehicleRegistrantMiddleName" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the vehicle registrant's middle name.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="VehicleRegistrantSurname"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the vehicle registrant's last name.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="VehicleRegistrantNameSuffix" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the suffix that follows a vehicle registrant’s full name and provides additional information about the person. There are academic, honorary, professional, and social name suffixes.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="VehicleRegistrantBirthDate"
				type="xsd:date">
				<xsd:annotation>
          <xsd:documentation>This element contains the birth date of the vehicle registrant.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="VehicleRegistrantGenderCode" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a code that identifies the gender of the vehicle registrant.
Valid options for this element are 'F'-Female or 'M'-Male.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="VehicleRegistrantDriverLicenseNumber" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the Driver License Number of the Vehicle Registrant.
</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="VehicleRegistrantLicenseStateAbbreviation"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the State Abbreviation of the State or Province where the vehicle's registrant’s driver’s license was issued.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="VehicleRegistrantId"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the id of the vehicle registrant.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="VehicleRegistrantOrganizationName" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contain the organization of the Vehicle Registrant.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0"
				name="BusinessPartyCharacteristic"
				type="bons1:BusinessPartyCharacteristic">
			</xsd:element>
			<xsd:element minOccurs="0" name="OrgTaxIdNumber"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a number assigned by a government entity where the organization or corporation has officially registered to conduct business.   In the US the 'Organization Tax Id Number'  is also known as the 'Federal Employer Identication Number'. or 'FEIN'
</xsd:documentation>
        </xsd:annotation>
			</xsd:element>



			<xsd:element minOccurs="0" name="MessageVehicleRegistrantId"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains an id assigned for the  lifetime of the message that will be used to identify the Vehicle Registrant.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="TypedAddress"
				type="bons0:TypedAddress" maxOccurs="unbounded">
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>