<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
	targetNamespace="http://ei/core/alliance_sbu_monthly_financial"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="AllianceSBUMonthlyFinancial">
		<xsd:sequence>
			<xsd:element name="CalendarMonthName" type="xsd:string"
				nillable="true" minOccurs="0">
				<xsd:annotation>
						<xsd:documentation>This element contains the name of the month.</xsd:documentation>
					</xsd:annotation>
			</xsd:element>
			<xsd:element name="CalendarYear" type="xsd:string"
				nillable="true" minOccurs="0">
				<xsd:annotation>
						<xsd:documentation>This element contains the calendar year.&#10;&#10;&#10;</xsd:documentation>
					</xsd:annotation>
			</xsd:element>
			<xsd:element name="AllianceFinancialValueBasisCode"
				type="xsd:string" nillable="true" minOccurs="0">
				<xsd:annotation>
						
					<xsd:documentation>This element identifies the Alliance financial data as Planned or Actual.
Valid values include:  'P' - Planned is the goal or 'A' - Actual is reality.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element name="AllianceFinancialValueTypeCode"
				type="xsd:string" nillable="true" minOccurs="0">
				<xsd:annotation>
						<xsd:documentation>This element contains a code that defines the type of the financial data.&#10;&#10;</xsd:documentation>
					</xsd:annotation>
			</xsd:element>
			<xsd:element name="AllianceFinancialValueTypeName"
				type="xsd:string" nillable="true" minOccurs="0">
				<xsd:annotation>
						<xsd:documentation>This element contains a name associated with the code that defines the type of the financial data.</xsd:documentation>
					</xsd:annotation>
			</xsd:element>
			<xsd:element name="AllianceFinancialValueTypeNote"
				type="xsd:string" nillable="true" minOccurs="0">
				<xsd:annotation>
						<xsd:documentation>This element contains a note, comment, or additional information about the financial type code.</xsd:documentation>
					</xsd:annotation>
			</xsd:element>
			<xsd:element name="AllianceFinancialValue"
				type="xsd:integer" nillable="true" minOccurs="0">
				<xsd:annotation>
						<xsd:documentation>This element conatins an Alliance financial value. </xsd:documentation>
					</xsd:annotation>
			</xsd:element>
			<xsd:element name="AllianceFinancialCommentText"
				type="xsd:string" nillable="true" minOccurs="0">
				<xsd:annotation>
						<xsd:documentation>This element contains user comments on financial types of Sponsorship and Marketing Expense which require some description.</xsd:documentation>
					</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>