<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
	targetNamespace="http://ei/core/billing_account_payment_summary"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="BillingAccountPaymentSummary">
		<xsd:annotation>
      <xsd:documentation>The Billing Account Payment Summary includes data about the Last, Current, and Next Payments for the current Term.   Once the Term amount is paid in full, the current and next payment amounts will reflect a zero balance.</xsd:documentation>
    </xsd:annotation>
		<xsd:sequence>
			<xsd:element minOccurs="0" name="LastPaymentDate"
				type="xsd:date">
				<xsd:annotation>
          <xsd:documentation>This element contains the date the last payment was made.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="LastPaymentAmount"
				type="xsd:decimal">
				<xsd:annotation>
          <xsd:documentation>This element contains the amount of the last payment that was made.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="CurrentInvoiceDate"
				type="xsd:date">
				<xsd:annotation>
          <xsd:documentation>This element contains the date the current invoice was sent.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="CurrentPaymentDueDate"
				type="xsd:date">
				<xsd:annotation>
          <xsd:documentation>This element contains the date the current payment is due.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="CurrentInstallmentPaymentAmount" type="xsd:decimal">
				<xsd:annotation>
          
        <xsd:documentation>This element contains the installment amount of the current payment.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="TermRemainingDueAmount"
				type="xsd:decimal">
				<xsd:annotation>
          <xsd:documentation>This element contains the remaining amount due for the policy term.
</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="CurrentPaymentExtensionIndicator" type="xsd:boolean">
				<xsd:annotation>
          <xsd:documentation>This element indicates if an extension has been given on the current payment during the pending cancel process.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>



			<xsd:element minOccurs="0" name="NextInvoiceDate"
				type="xsd:date">
				<xsd:annotation>
          <xsd:documentation>This element contains the date the next bill will be sent.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="NextPaymentDueDate"
				type="xsd:date">
				<xsd:annotation>
          <xsd:documentation>This element contains the date the next payment is due.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="NextInstallmentPaymentAmount" type="xsd:decimal">
				<xsd:annotation>
          
        <xsd:documentation>This element contains the next installment payment amount.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="NextPaymentTermRemainingDueAmount" type="xsd:decimal">
				<xsd:annotation>
          
        <xsd:documentation>This element contains the remaining amount due for the term at the time the next installment payment is due.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0"
				name="NextPaymentExtensionIndicator" type="xsd:boolean">
				<xsd:annotation>
          <xsd:documentation>This element indicates if an extension has been given on the next payment.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="SuspenseAmount"
				type="xsd:decimal"><xsd:annotation><xsd:documentation>This element contains the amount that is in suspense.</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>