<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ei/core/billing_account"
	xmlns:Q1="http://ei/core/bill_payor"
	xmlns:bons1="http://ei/core/addressx5"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:import namespace="http://ei/core/addressx5"
		schemaLocation="AddressX5.xsd">
	</xsd:import>
	<xsd:import namespace="http://ei/core/bill_payor"
		schemaLocation="BillPayor.xsd">
	</xsd:import>

	<xsd:complexType name="BillingAccount">
		<xsd:annotation>
      <xsd:documentation>A Billing Account is created to group together multiple Policies and their payments that have a common Bill Payor.</xsd:documentation>
    </xsd:annotation>
		<xsd:sequence>
			<xsd:element minOccurs="0" name="BillPayor"
				type="Q1:BillPayor">
			</xsd:element>
			<xsd:element minOccurs="0"
				name="BillAccountInsuredMailingAddress" type="bons1:Address">
			</xsd:element>


			<xsd:element minOccurs="0" name="BillAccountNumber"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the Chubb billing account, which is used to track payments on one or more Chubb Policies for an Insured.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="BillAccountId"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a unique identifier assigned to the Billing Account.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0" name="BillAccountStatusName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the name of the billing account status, including active(balance &gt;$0), Inactive (current balance = $0) or suspended billing.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="NonPaymentLegalIndicator"
				type="xsd:boolean">
				<xsd:annotation>
          <xsd:documentation>This element indicates if any Policy on the account has been turned over to legal for non-payment.



</xsd:documentation>
        </xsd:annotation>
			</xsd:element>


			<xsd:element minOccurs="0"
				name="EmployeeBillAccountIndicator" type="xsd:boolean">
				<xsd:annotation>
          <xsd:documentation>This element indicates if this billing account is for a Chubb employee.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PendingCancelIndicator"
				type="xsd:boolean">
				<xsd:annotation>
          <xsd:documentation>This element indicates if payments are past due on one or more Policies in the billing account and as a result at least one Policy is pending cancellation.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="SplitBillIndicator"
				type="xsd:boolean">
				<xsd:annotation>
          
        <xsd:documentation>This element indicates if there are policies on this billing account that are also on another billing account.   This occurs when multiple bill payors are responsible for payments on the same policy.   Examples would include when there are multiple homes with different mortgagees or a home with a mortgagee, but the Insured also has other coverages on the same policy.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="NonPaymentNoticeCount"
				type="xsd:integer">
				<xsd:annotation>
          <xsd:documentation>This element contains the count of nonpayment notices sent to a billing account.  A notice is sent approximately one week after the payment due date, but this timeframe does vary based on state regulations.  The time period considered for setting this count can vary and will be specified for each service.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0"
				name="ElectronicBillEnrollmentStatusCode" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element indicates if the bill payor should receive an electronic bill, otherwise they will receive a paper bill.
Valid values inclued 'A'- Active electronic bill, otherwise(space) paper bill</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="BillAccountValidationId"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains data that allows the validation of the billing account, it typically contains the zip code of the Bill Payor.   </xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="LoanNumber"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the number that identifies a loan.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="BillAccountInsuredName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the Insured Name aggregated across multiple policies to the Billing Account level.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="BillAccountFrequencyCode"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the frequnecy which the account should be billed.
Valid values include  'AN' - ANNUALLY, 'BM' - BI-MONTHLY, 'BW' - BI-WEEKLY.  'MO' - MONTHLY,  'QT' - QUARTERLY,  'SA' - SEMI-ANNUALLY, 'SM' - SEMI-MONTHLY or 'WK'- WEEKLY.
</xsd:documentation>
        </xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0" name="CPNumber"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element is the number assigned to the contract partcipant. A contract partcipant may be, but is not limited to, an
insured, a prospective insured, a risk manager, an additional insured, or a Chubb resource.</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>