<?xml version="1.0" encoding="UTF-8"?><xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://ei/core/birth_date_information">
	<xsd:complexType name="BirthDateInformation">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="ApproximateBirthDateIndicator" type="xsd:boolean">
        <xsd:annotation>
          <xsd:documentation>This element indicates whether the Birth Date is an approximate date.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="IndividualBirthDate" type="xsd:date">
				<xsd:annotation>
          <xsd:documentation>This element contains the date the individual was born.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>