<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ei/core/business_contact_type"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="BusinessContactType">
		<xsd:sequence>
			<xsd:element name="ContactTypeCode" type="xsd:string"
				nillable="true" minOccurs="0">
				<xsd:annotation>
						<xsd:documentation>This element contains a code which identifies the type of contact that an individual is in relation to the business.   Valid values  for this element can be found in application specific reference tables.</xsd:documentation>
					</xsd:annotation>
			</xsd:element>
			<xsd:element name="ContactTypeDescription" type="xsd:string"
				nillable="true" minOccurs="0">
				<xsd:annotation>
						
					<xsd:documentation>This element contains a description which identifies the type of contact that an individual is in relation to the business.   Valid values  for this element can be found in application specific reference tables.</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>