<?xml version="1.0" encoding="UTF-8"?><xsd:schema targetNamespace="http://ei/core/business_party_covered_risk_interest" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="BusinessPartyCoveredRiskInterest">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="ProductComponentName" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>This element contains the name of the Product Component.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="BPCoveredRiskInterestIndicator" type="xsd:boolean">
				<xsd:annotation>
          <xsd:documentation>This element indicates if a business party is concerned a particular covered risk.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>