<?xml version="1.0" encoding="UTF-8"?><xsd:schema targetNamespace="http://ei/core/capturable" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="Capturable">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="CapturableClassificationCode" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a code that identifies the type of capturable.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="CapturableName" type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element contains the name of a capturable for a Policy.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="CapturableValue" type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element contains the value of a policy capturable associated with a capturable name.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="CapturableAmount" type="xsd:decimal">
				<xsd:annotation>
          <xsd:documentation>This element contains the amount associated with the Policy Capturable Name.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="CapturableIndicator" type="xsd:boolean">
				<xsd:annotation>
          <xsd:documentation>This element contains the an indicator associated with the Policy Capturable Name.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0" name="CapturableDate" type="xsd:date">
				<xsd:annotation>
          
        <xsd:documentation>This element contains the date associated with the Policy Capturable Name.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0" name="CapturableCurrencyCode" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a code which indentifies the currency of the Policy Capturable Amount.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="CapturableAmountTypeName" type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element describes the type of data contained in the Policy Caputurable Amount.
Valid values for this element include Currency, Distance, Time, and Quantity.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="UnitOfMeasure" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element specifies the measure for the Amount provided for Distance, Time, and Quantity Amounts. 
Some valid values for this element would include day, weeks, months.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>

		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>