<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
	targetNamespace="http://ei/core/claim_life_cycle_stage_property"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="ClaimLifeCycleStageProperty">
		<xsd:annotation><xsd:documentation>This object is used for additional properties for a Claim life cycle stage.</xsd:documentation></xsd:annotation>
		<xsd:sequence>
			<xsd:element minOccurs="0"
				name="ClaimLifeCycleStagePropertyName" type="xsd:string"><xsd:annotation><xsd:documentation>This element contains the name of a claim life cycle stage property.  </xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" maxOccurs="1"
				name="ClaimLifeCycleStagePropertyValue" type="xsd:string"><xsd:annotation><xsd:documentation>This element contains the value associated to a specific claim life cycle stage property.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="ClaimLifeCycleStagePropertyDate" type="xsd:date"><xsd:annotation><xsd:documentation>This element contains the date associated to a specific claim life cycle stage property.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="ClaimLifeCycleStagePropertyIndicator" type="xsd:boolean"><xsd:annotation><xsd:documentation>This element contains an indicator associated to a specific claim life cycle stage property.</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>