<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ei/core/dfi_account"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="DFIAccount">
		<xsd:sequence>

			<xsd:element minOccurs="0" name="DFIAccountCode"
				type="xsd:string">
				<xsd:annotation>
          
        
        
        <xsd:documentation>This element is used to identify specific types of business underwritten by DFI. 
This element is also known as Policy Account Identification Code.
The E1T00071 Corporate Table contains valid values for this element in the &quot;DFI_ACCT_C&quot; column.
					</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="DFIAccountAbbreviation"
				type="xsd:string">
				<xsd:annotation>
          
        
        <xsd:documentation>This element is the abbreviated name of a commercial account or financial institution.  
This element specifically identifies the type of insured underwritten by the Department of Financial Institutions.
The E1T00071 Corporate Table contains valid values for this element in the "DFI_ACCT_AB" column.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="DFIAccountShortName"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element is the short name associated with the *Department of Financial Institutions Account Code*.
The E1T00071 Corporate Table contains valid values for this element in the &quot;DFI_ACCT_SHRT_NA&quot; column.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="DFIAccountMixedCaseShortName" type="xsd:string">
				<xsd:annotation><xsd:documentation>This element is the short name associated with the *Department of Financial Institutions Account Code* in mixed case format.
The E1T00071 Corporate Table contains valid values for this element in the &quot;DFI_ACCT_MXCSH_NA&quot; column.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="DFIAccountName"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element is the name associated with the *Department of Financial Institutions Account Code*.
The E1T00071 Corporate Table contains valid values for this element in the &quot;DFI_ACCT_NA&quot; column.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="DFIAccountMixedCaseName"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element is the name associated with the *Department of Financial Institutions Account Code* in mixed case format.
The E1T00071 Corporate Table contains valid values for this element in the &quot;DFI_ACCT_MXC_NA&quot; column.</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>