<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://ei/core/exposurex2"
	xmlns:bons0="http://ei/core/customization">
	<xsd:import schemaLocation="Customization.xsd"
		namespace="http://ei/core/customization">
	</xsd:import>
	<xsd:complexType name="Exposure">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="ExposureTypeReferenceCode"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a code that identifies a specific exposure type.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ExposureName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a name that identifies a specific exposure type.  </xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ExposureAmount"
				type="xsd:decimal">
				<xsd:annotation>
          <xsd:documentation>This element contains the value of the property being insured to which the rates for the perils are applied to develop premium.

</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ExposureCurrencyCode"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a code which indentifies the currency of the exposure amount.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ExposureTypeValue"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a value associated to a particular exposure type.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0" name="ExposureAmountTypeName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element describes the type of data contained in the Exposure amount.
Valid values for this element include Currency, Distance, Time, and Quantity.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="UnitOfMeasure"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element specifies the measure for the Amount provided for Distance, Time, and Quantity Amounts. 
Some valid values for this element would include day, weeks, months.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ExposureRate"
				type="xsd:decimal">
				<xsd:annotation>
          <xsd:documentation>This element contains the Rate that will be applied to determine the Exposure Amount.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ExposureCode"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This contains a code associated with a particular exposure.  It is used on conjunction with the name of the exposure.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="Customization"
				type="bons0:Customization" maxOccurs="unbounded">
			</xsd:element>
			<xsd:element minOccurs="0" name="PremiumBasisAmount"
				type="xsd:decimal"><xsd:annotation><xsd:documentation>&lt;BR&gt;
&lt;P class=MsoNormal style=&quot;MARGIN: 0in 0in 0pt&quot;&gt;&lt;SPAN style='FONT-SIZE: 10pt; FONT-FAMILY: &quot;Arial&quot;,&quot;sans-serif&quot;'&gt;This element contains the amount&amp;nbsp;used as&amp;nbsp;the basis of the premium; it is used to calculate other financial amounts.&lt;?xml:namespace prefix = &quot;o&quot; ns = &quot;urn:schemas-microsoft-com:office:office&quot; /&gt;&lt;o:p&gt;&lt;/o:p&gt;&lt;/SPAN&gt;&lt;/P&gt;
&lt;br/&gt;</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>