<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://ei/core/insurerx2"
	xmlns:bons0="http://ei/core/business_party_characteristic">
	<!-- Insurer -->
	<xsd:import schemaLocation="BusinessPartyCharacteristic.xsd"
		namespace="http://ei/core/business_party_characteristic">
	</xsd:import>
	<xsd:complexType name="Insurer">
		<xsd:annotation>
			<xsd:documentation>This business object is information pertaining to the Chubb group.</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element minOccurs="0" name="InsurerName"
				type="xsd:string">
				<xsd:annotation>
					
				<xsd:documentation>
This element specifies the incorporated, or legal name, of an indivdual company that issues policies within The Chubb Insurance Group (also known as Writing Company Name). 
The E1T00011 Corporate Table contains valid values for this element in the "WTE_CO_NA" or the "WTE_CO_MXC_NA" column.
					</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="InsurerAbbreviation"
				type="xsd:string">
				<xsd:annotation>
					<xsd:documentation>
This element specifies the abbreviation for an indivdual company that issues policies within The Chubb Insurance Group (also known as Writing Company Abbreviation). 
The E1T00011 Corporate Table contains valid values for this element in the "WTE_CO_AB" column. 
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="InsurerNumber"
				type="xsd:string">
				<xsd:annotation>
					<xsd:documentation>
This element specifies the code for an indivdual company that issues policies within The Chubb Insurance Group (also known as Writing Company Code). 
The E1T00011 Corporate Table contains valid values for this element in the "WTE_CO_C" column. 
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="AtlasStatutoryCompanyCode"
				type="xsd:string"><xsd:annotation><xsd:documentation>This symbol identifies the statutory company code as known in Atlas, within the Chubb Group, in which the policy is
underwritten. The &quot;ATL_STUY_CO_CD&quot; column contains valid values for this on the E1T00011 Writing Company Table.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="BusinessPartyCharacteristic"
				type="bons0:BusinessPartyCharacteristic" maxOccurs="unbounded">
			</xsd:element>
			<xsd:element minOccurs="0" name="NCCIGroupCode"
				type="xsd:string"><xsd:annotation><xsd:documentation>This symbol identifies a Chubb Group when exchanging data with the National Council or Associates.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="NCCICompanyCode"
				type="xsd:string"><xsd:annotation><xsd:documentation>This symbol identifies an individual insurance carrier {company} when exchanging data with the National Council or
Associates.</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>