<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ei/core/issued_policy_form"
	xmlns:bons1="http://ei/core/managed_document"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:bons0="http://ei/core/customization">
	<xsd:import schemaLocation="Customization.xsd"
		namespace="http://ei/core/customization">
	</xsd:import>
	<xsd:import namespace="http://ei/core/managed_document"
		schemaLocation="ManagedDocument.xsd">
	</xsd:import>
	<xsd:complexType name="IssuedPolicyForm">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="FormDocument"
				type="bons1:ManagedDocument">
			</xsd:element>

			<xsd:element minOccurs="0" name="Customization"
				type="bons0:Customization" maxOccurs="unbounded">
			</xsd:element>
			<xsd:element minOccurs="0" name="FormSequenceNumber"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element indentifies the order in which forms are attached to a policy or transaction.

</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="SourceSystemFormNumber"
				type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element contains the form number as it is known by the source system</xsd:documentation></xsd:annotation>
			</xsd:element>


			<xsd:element minOccurs="0" name="FormProductTitleName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element identifies the product-specific title for a corporate form.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="FormRevisionEditionYearMonth" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the year and month the form text was last modified.

</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="VersionNumber"
				type="xsd:int">
				<xsd:annotation>
          <xsd:documentation>This element identifies a particular version of the information.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="FormModifiedDate"
				type="xsd:date">
				<xsd:annotation>
          <xsd:documentation>This element contains the date the form was created or last modified.   A form with variable data will always have a new date when the form is attached to the Policy.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="FormModifiedTime"
				type="xsd:time">
				<xsd:annotation>
          <xsd:documentation>This element contains the time the form was created or last modified.   A form with variable data will always have a new date &amp; time when the form is attached to the Policy.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0" name="FormLanguageCode"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a code which identifies the particular language that a form is printed in.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PhysicalPageOptionName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element determines how the physical page will be printed.  
Valid values include:
'Simplex' - One side of the page
'Duplex' - Both sides of the page.

</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="VariableFormIndicator"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element indicates if a form has any variable fields.
Valid values for this element are 'Y' or 'N'.
</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ManuscriptFormIndicator"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element indicates if a form is manuscripted.
Valid values for this element are 'Y' or 'N'.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>

		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>