<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ei/core/loss_payee"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:bons2="http://ei/core/typed_addressx3"
	xmlns:bons0="http://ei/core/business_party_characteristic">
	<xsd:import schemaLocation="BusinessPartyCharacteristic.xsd"
		namespace="http://ei/core/business_party_characteristic">
	</xsd:import>
	<xsd:import schemaLocation="TypedAddressX3.xsd"
		namespace="http://ei/core/typed_addressx3">
	</xsd:import>

	<xsd:complexType name="LossPayee">
		<xsd:sequence>
			<xsd:element maxOccurs="unbounded" minOccurs="0"
				name="TypedAddress" type="bons2:TypedAddress">
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0"
				name="BusinessPartyCharacteristic"
				type="bons0:BusinessPartyCharacteristic">
			</xsd:element>
			<xsd:element minOccurs="0" name="MessageLossPayeeId"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains an id assigned for the  lifetime of the message that will be used to identify the Loss Payee.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="LossPayeeNumber"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a sequential number that is incremented each time a new loss payee is added.   </xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="LossPayeeName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the name of the Loss Payee.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>


			<xsd:element minOccurs="0" name="EnterpriseBPRoleCode"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a code that represents the function or position a specific business party may play on a Policy or Service Offering for a given enterprise.
The E1T01611 Corporate Table contains valid values for this element in the "ENTRP_BP_ROLE_C" column. 


</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="EnterpriseBPRoleName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the function or position a specific business party may play on a Policy or Service Offering for a given enterprise.
The E1T01611 Corporate Table contains valid values for this element in the "ENTRP_BP_ROLE_NA" column. </xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="BPEntityTypeName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element identifies the legal nature of the business party. (i.e., individual or organization).</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="LoanNumber"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the number that identifies a loan.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PolicyCopyIndicator"
				type="xsd:boolean">
				<xsd:annotation>
          <xsd:documentation>This element indicates if a copy of the Policy is to be sent to a Business Party.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>


		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>