<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ei/core/medical_institutionx2"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:bons0="http://ei/core/addressx3">
	<xsd:import schemaLocation="AddressX3.xsd"
		namespace="http://ei/core/addressx3">
	</xsd:import>
	<xsd:complexType name="MedicalInstitution">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="MedicalInstitutionName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the name of a medical institution, which could be hospital , clinic or laboratory.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="Address"
				type="bons0:Address">
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>