<?xml version="1.0" encoding="UTF-8"?><xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://ei/core/nationality_information">
	<xsd:complexType name="NationalityInformation">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="NationalityDescription" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>This element describes an individual's status of belonging to a particular nation by birth or nationalization.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ISOCountryCode" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>This element is the abbreviation used by the International Standards Organization (ISO) that identifies a country, nation
or political state. The E1T00101 Corporate Table contains valid values for this element in the "ISO_CNTRY_C" column.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>