<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://ei/core/performer"
	xmlns:bons0="http://ei/core/addressx2">
	<xsd:import schemaLocation="AddressX2.xsd"
		namespace="http://ei/core/addressx2">
	</xsd:import>
	<xsd:complexType name="Performer">
		<xsd:annotation><xsd:documentation> A Performer is a person or legal entity internal to Chubb or designated by Chubb to play a role on a Policy or Claim.</xsd:documentation></xsd:annotation>
		<xsd:sequence>
			<xsd:element minOccurs="0" name="Address"
				type="bons0:Address">
			</xsd:element>
			<xsd:element minOccurs="0" name="BusinessName"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains the name of a business.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="BusinessEntityIndicator"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element indicates if something is a business entity.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="GivenName"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains a person's first name.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="MiddleInitial"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains the first letter from a person's middle name.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="Surname"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains a person's last name.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="NameSuffix"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains the suffix that follows a person’s full name and provides additional information about the person. There are academic, honorary, professional, and social name suffixes.
</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PerformerRoleTypeCode"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains a code that identifies the role type of the performer.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PerformerRoleTypeName"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains a name that identifies the role type of the performer.</xsd:documentation></xsd:annotation>
			</xsd:element>			<xsd:element minOccurs="0" name="PerformerNumber"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains the number of the performer.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PerformerCode"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains a code used to identify a performer.</xsd:documentation></xsd:annotation>
			</xsd:element>			<xsd:element minOccurs="0" name="PhoneNumber"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains a person's phone number.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="FaxNumber"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains a person's fax number.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="EmailAddress"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains a person's e-mail address.</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>
