<?xml version="1.0" encoding="UTF-8"?><xsd:schema targetNamespace="http://ei/core/premium_apportionment" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="PremiumApportionment">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="PremiumApportionmentGroupCode" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the group, which can be a state,  for this portion of the premium.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PremiumApportionmentPercent" type="xsd:decimal">
				<xsd:annotation>
          <xsd:documentation>This element contains the percent of the premium for this portion. </xsd:documentation>
        </xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>