<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://ei/core/rating_territory">
	<xsd:complexType name="RatingTerritory">
		<xsd:annotation>
      <xsd:documentation>This element contains the name of the line of business territory.</xsd:documentation>
    </xsd:annotation>
		<xsd:sequence>
			<xsd:element minOccurs="0" name="RatingTerritoryName"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains the name of the Rating Territory.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="RatingTerritoryCode"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the code for the Line of Business Territory, for the Line Of Business Territory contained in the name element.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>
