<?xml version="1.0" encoding="UTF-8"?><xsd:schema targetNamespace="http://ei/core/risk_rating_parameter" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="RiskRatingParameter">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="RiskRatingParameterName" type="xsd:string">
				<xsd:annotation>
          
        
        <xsd:documentation>This element contains the name of the risk/rating parameter.  The value set for any/all use of this abstract element is set within the context of a specific service.  
</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="RiskRatingParameterValue" type="xsd:string">
				<xsd:annotation>
          
        
        <xsd:documentation>This element contains a value associated with the RiskRatingParameterName.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="RiskRatingParameterAmount" type="xsd:decimal">
				<xsd:annotation>
          
        
        <xsd:documentation>This element contains an amount associated with the  RiskRatingParameterName.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="RiskRatingParameterIndicator" type="xsd:boolean">
				<xsd:annotation>
          
        
        <xsd:documentation>This element contains an indicator associated with the  RiskRatingParameterName.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="RiskRatingParameterDate" type="xsd:date">
				<xsd:annotation>
          
        
        <xsd:documentation>This element contains a date associated with the  RiskRatingParameterName.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="RiskRatingParameterCurrencyCode" type="xsd:string">
				<xsd:annotation>
          
        
        <xsd:documentation>This element contains a code which indentifies the currency of the RiskRatingParameterAmount.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="RiskRatingParameterAmountTypeName" type="xsd:string">
				<xsd:annotation>
          
        
        <xsd:documentation>This element describes the type of data contained in the RiskRatingParameterAmount.
Valid values for this element include Currency, Distance, Time, and Quantity.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0" name="UnitOfMeasure" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element specifies the measure for the Amount provided for Distance, Time, and Quantity Amounts. 
Some valid values for this element would include day, weeks, months.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>