<?xml version="1.0" encoding="UTF-8"?><xsd:schema targetNamespace="http://ei/core/state_mandated_information" xmlns:bons0="http://ei/core/state_mandated_parameter" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:import namespace="http://ei/core/state_mandated_parameter" schemaLocation="StateMandatedParameter.xsd"/>
	<xsd:complexType name="StateMandatedInformation">
		<xsd:sequence>

			<xsd:element maxOccurs="unbounded" minOccurs="0" name="StateMandatedParameter" type="bons0:StateMandatedParameter">
			</xsd:element>
			<xsd:element minOccurs="0" name="SourceSystemName" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element identifies the data entry application (Policy, Claim, other) which originated the transaction or other data feed.  The application would be the source of detailed information and history about the policy, claim, etc.
The E1T00871 Corporate Table contains valid values for this element in the "SYS_SRC_NAME" column. </xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ChubbStateMandatedCode" type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element contains a code assigned to the state mandated information.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ChubbStateMandatedDescription" type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element contains the description of the state mandated information.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="StateOrProvinceCode" type="xsd:string">
			</xsd:element>

			<xsd:element minOccurs="0" name="MessageChubbStateMandatedId" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>This element contains an Id assigned for the  lifetime of the message that will be used to identify the State Mandated Information.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>