<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ei/core/survey_contact"
	xmlns:bons0="http://ei/core/business_contact"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:import namespace="http://ei/core/business_contact"
		schemaLocation="BusinessContact.xsd">
	</xsd:import>
	<xsd:complexType name="SurveyContact">
		<xsd:sequence>

			<xsd:element minOccurs="0" name="BusinessContact"
				type="bons0:BusinessContact" maxOccurs="unbounded">
			</xsd:element>
			<xsd:element minOccurs="0" name="SurveyContactTypeName"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains the name of the type of survey contact.
Some valid options for this element are 'Producer', 'Insured', 'Location'.</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>