spring:
  application:
    name: loc-service6

server:
  port: 8086

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level [%X{correlationId}] %logger{36} - %msg%n"

security:
  requireApiKey: false
providers:
  mock:
    baseUrl: localhost:8091
