<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ei/core/business_party"
	xmlns:bons0="http://ei/core/individual_name"
	xmlns:bons1="http://ei/core/typed_addressx2"
	xmlns:bons2="http://ei/core/telecomm_electronic_address"
	xmlns:bons4="http://ei/core/individual_identifier"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:import namespace="http://ei/core/telecomm_electronic_address"
		schemaLocation="TelecommElectronicAddress.xsd" />
	<xsd:import namespace="http://ei/core/typed_addressx2"
		schemaLocation="TypedAddressX2.xsd">
	</xsd:import>
	<xsd:import namespace="http://ei/core/individual_name"
		schemaLocation="IndividualName.xsd">
	</xsd:import>
	<xsd:import namespace="http://ei/core/individual_identifier"
		schemaLocation="IndividualIdentifier.xsd">
	</xsd:import>



	<xsd:complexType name="BusinessParty">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="IndividualIdentifier"
				type="bons4:IndividualIdentifier">
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0"
				name="IndividualName" type="bons0:IndividualName">
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0"
				name="BPTypedAddress" type="bons1:TypedAddress">
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0"
				name="BPTelecommElectronicAddress"
				type="bons2:TelecommElectronicAddress">
			</xsd:element>
			<xsd:element minOccurs="0" name="BPDurableKey"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains an unique identifier assigned to an instance of a business party for its entire lifetime.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="BPTypeCode"
				type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element identifies a type of business party.
The E1T01581 Corporate Table contains valid values for this element in the 'BP_TY_C' column. </xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>