<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://ei/core/cache_key">
	<xsd:complexType name="CacheKey">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="CacheKey"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element is unique key to indentify a string of data that is cached.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ServiceInterfaceName"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element identifies the name of the service interface (e.g. ProducerValidationPRD1X2).</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>
