<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ei/core/event_property"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="EventProperty">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="EventPropertyName"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element describes the name of the property associated with the event.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="EventPropertyValue"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element identifies the  value  associated with the EventPropertyName.</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>