<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://ei/core/medical_device">
	<xsd:complexType name="MedicalDevice">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="MedicalDeviceId"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a unique number used to identify a medical device.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="MedicalDeviceNameSequenceNumber" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the sequence number assigned to a particular medical device name.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="MedicalDeviceName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the name of a medical device.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="MedicalDeviceModelId"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a unique number used to identify a medical device model.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="MedicalDeviceModelName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the name of a medical device model.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="MedicalDeviceModelNameSequenceNumber" type="xsd:string"><xsd:annotation><xsd:documentation>This element contains the sequence number assigned to a particular medical device model name.</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>
