<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ei/core/policy_event"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">



	<xsd:complexType name="PolicyEvent">
		<xsd:sequence>



			<xsd:element minOccurs="0" name="PolicyEventTypeCode"
				type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element contains a code to identify the type of policy event. 
Some valid values include STATUSCHG and UPDATENAME.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PolicyEventTypeName"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains a name to identify the type of policy event. 
 </xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PolicyEventDate"
				type="xsd:date">
				<xsd:annotation>
          <xsd:documentation>This element identifies the date of the policy event.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0" name="WIPInsuredNumber"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element is the WIP ID number for the Insured.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ControlNumber"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element is a unique identifier for each policy or submission.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="PolicyTypeEnglishAbbreviation" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element is the name assigned to a policy that represents the type of insurance contract. 
The Corporate table E1T00221 contain the valid values for this element if the "POL_TY_AB" column.
					</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PolicyNumber"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element identifies an insurance contract.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PolicyTypeCode"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element identifies the type of the insurance contract with a code.
The Corporate table E1T00221 contain the valid values for this element in the "POL_TY_C" column.
					</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PolicyTypeSubCode"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>The element is used to divide Policy Type Code in order to provide more categories for some insurance contracts.  (This is also known as PolicySubTypeCode.)
The Corporate table E1T00221 contain the valid values for this element if the "POL_SUB_TY_C" column.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>


			<xsd:element minOccurs="0" name="InceptionDate"
				type="xsd:date">
				<xsd:annotation>
          <xsd:documentation>This element specifies the inception date of a policy term. </xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ExpirationDate"
				type="xsd:date">
				<xsd:annotation>
          <xsd:documentation>This element specifies the expiration date of a policy term. 
				</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="OfferingNumber"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element is a unique identifier for each policy or submission in the Client / WIP system.
					</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="OfferingDB2Timestamp"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element is a unique identifier for each policy term in the Client/WIP System.
Values for this element are in a DB2 timestamp format: yyyy-mm-dd-hh.mm.ss.zzzzzz. </xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="OfferingStatusCode"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element identifies via a code the current status on an Offering.
The E1T00831 Corporate Table contains valid values for this element in the "OFFRG_STAT_C" column.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="OfferingStatusName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element describes the current status on an Offering. 
The E1T00831 Corporate Table contains valid values for this element in the "OFFRG_STAT_NA" column.
					</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="LastOfferingStatusCode"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element identifies via a code the prior status on an Offering.
The E1T00831 Corporate Table contains valid values for this element in the "OFFRG_STAT_C" column.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="LastOfferingStatusName"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element describes the prior status on an Offering. 
The E1T00831 Corporate Table contains valid values for this element in the &quot;OFFRG_STAT_NA&quot; column.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ProducerNumber"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element is a Chubb ID number for an agent or broker
This is also known as the Agent Number.
The AGTAGDA1 Corporate Table contains valid values for this element in the "AGT_N" column.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ProducerSubNumber"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element identifies a subdivision of business within an agent or broker.
This also known as Sub Agent Number or Sub Producer Number.
The AGTAGDA1 Corporate Table contains valid values for this element in the "SUB_AGT_N" column.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ProducingBranchNumber"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element specifies the number of the Chubb office that receives premium credit for a policy.
The E1T00031 Corporate Table contains valid values for this element in the "BR_LOC_N" column.
					</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ProducingDepartmentNumber"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element specifies the number of the department that produces a policy.  
Valid values for this element may be referenced from several Corporate Tables:
The E1T00381 Corporate Table contains valid values for this element in the "DEPT_N" column. 
The E1T00061 Corporate Table contains valid values for this element in the "UW_RESPON_DEPT_ N" column.
The E1T00051 Corporate Table contains valid values for this element in the "DEPT_SECTN_N" column.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ServiceAreaCode"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element identifies the customer group or practice that is responsible for the service of a policy.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>




			<xsd:element minOccurs="0" name="ZoneGroupAbbreviation"
				type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element contains the abbreviation of the group of Chubb defined zonal groupings.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ZoneNumber"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a numeric value that identifies a Chubb defined territory.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0" name="CancellationReasonCode"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element is a code which identifies  why a policy was cancelled. 
The Corporate table E1T00281 contains the valid values for this element in the "CANC_RSN_C" column.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="CancellationDate"
				type="xsd:date">
				<xsd:annotation>
          <xsd:documentation>This element is the date the policy or bond ceases to provide protection for the coverage or policy.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="QuoteDeadRiskReasonCode"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element identifies the manner in which a submission was lost.  Valid values for this element are defined in corporate table 
E1T00281 in column DEAD_RSK_RSN_C.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0" name="QuoteDeadRiskDate"
				type="xsd:date">
				<xsd:annotation>
          <xsd:documentation>This element identifies when a quote is no longer an active item, due to being rejected, declined or cancelled. </xsd:documentation>
        </xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>