<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
	targetNamespace="http://ei/core/service_process_classification"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="ServiceProcessClassification">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="ProcessClassificationCode"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element allows the source of the data to be classified so a specific action(process) can be taken based on what system and/or CCM is supplying the data.  
The E1T01631 Corporate Table contains valid values for this element in the "SVCPROC_CLS_C" column.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="ProcessClassificationAbbreviation" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element allows the source of the data to be classified so a specific action(process) can be taken based on what system and/or CCM is supplying the data.  
The E1T01631 Corporate Table contains valid values for this element in the "SVCPROC_CLS_AB" column.



      </xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ProcessClassificationName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element allows the source of the data to be classified so a specific action(process) can be taken based on what system and/or CCM is supplying the data.
The E1T01631 Corporate Table contains valid values for this element in the "SVCPROCCLSSHRT_NA" column.


</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="ProcessClassificationMixedCaseName" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element allows the source of the data to be classified so a specific action(process) can be taken based on what system and/or CCM is supplying the data.  
The E1T01631 Corporate Table contains valid values for this element in the "SVCPROCCLSMXCSH_NA" column.



</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ProcessClassDisplayName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element allows the source of the data to be classified so a specific action(process) can be taken based on what system and/or CCM is supplying the data.
The E1T01631 Corporate Table contains valid values for this element in the "SVCPROCCLS_NA " column.

</xsd:documentation>
        </xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0"
				name="ProcessClassMixedCaseDisplayName" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element allows the source of the data to be classified so a specific action(process) can be taken based on what system and/or CCM is supplying the data.
The E1T01631 Corporate Table contains valid values for this element in the "SVCPROCCLS_MXC_NA " column.



</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="ProcessClassificationCommentText" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains any comments related to the Process Classification.
The E1T01631 Corporate Table contains valid values for this element in the "SVCPROCCLSCMNT_TXT" column.


</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ProcessLOBDescription"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element describes a process class used in service for a line of business.
The E1TA1631 Corporate Table contains valid values for this element in the &quot;SYS_LOB_DE&quot; column.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="ProcessBusinessFunctionName" type="xsd:string"><xsd:annotation><xsd:documentation>This element is the name of the common unit of business work used in the service of a process class.
The E1TA1631 Corporate Table contains valid values for this element in the &quot;SVCPROCBUSFUNC_NA&quot; column.</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>