<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
	targetNamespace="http://ei/core/text_analytics_concept_group_result"
	xmlns:bons1="http://ei/core/text_analytics_concept_result"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:import namespace="http://ei/core/text_analytics_concept_result"
		schemaLocation="TextAnalyticsConceptResult.xsd" />
	<xsd:complexType name="TextAnalyticsConceptGroupResult">
		<xsd:sequence>
			<xsd:element maxOccurs="unbounded" minOccurs="0"
				name="TextAnalyticsConceptResult"
				type="bons1:TextAnalyticsConceptResult">
			</xsd:element>
			<xsd:element minOccurs="0"
				name="TextAnalyticsConceptGroupName" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the name of a concept group, which is a collection of concepts.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>

		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>