<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bons0="http://ei/core/taxing_jurisdiction" xmlns:bons1="http://ei/core/rating_territory" xmlns:bons2="http://ei/location/location_information" xmlns:bons3="http://ei/location/standardized_addressx1" xmlns:bons5="http://ei/core/hazardous_area" targetNamespace="http://ei/location/location">
    <xsd:import namespace="http://ei/core/taxing_jurisdiction" schemaLocation="TaxingJurisdiction.xsd"/>
	<xsd:import namespace="http://ei/location/standardized_addressx1" schemaLocation="StandardizedAddressX1.xsd">
	</xsd:import>
	<xsd:import namespace="http://ei/location/location_information" schemaLocation="LocationInformation.xsd"/>

	<xsd:import namespace="http://ei/core/rating_territory" schemaLocation="RatingTerritory.xsd"/>
	<xsd:import namespace="http://ei/core/hazardous_area" schemaLocation="HazardousArea.xsd"/>

	<xsd:complexType name="Location">
		<xsd:sequence>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="RatingTerritory" type="bons1:RatingTerritory">
			</xsd:element>
			<xsd:element minOccurs="0" name="LocationInformation" type="bons2:LocationInformation">
			</xsd:element>
			<xsd:element minOccurs="0" name="StandardizedAddress" type="bons3:StandardizedAddress">
			</xsd:element>

			<xsd:element maxOccurs="unbounded" minOccurs="0" name="TaxingJurisdiction" type="bons0:TaxingJurisdiction">
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="HazardousArea" type="bons5:HazardousArea">
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>
