spring:
  application:
    name: loc-service10

server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level [%X{correlationId}] %logger{36} - %msg%n"
  level:
    org.apache.camel: DEBUG
    org.apache.camel.component.http: DEBUG
    org.springframework.web: DEBUG

camel:
  springboot:
    routes-include-pattern: classpath:routes/*.yaml
  main:
    routes-include-pattern: classpath:routes/*.yaml

providers:
  mock:
    baseUrl: http://localhost:8091
dependencies2:
  base: c:\CHUBB\IA\Alberto_Recreation_Latest\TRAE-CHUBB\loc3x1-camel-route\CHUBB\Dependencies2
  baseUri: file:///c:/CHUBB/IA/Alberto_Recreation_Latest/TRAE-CHUBB/loc3x1-camel-route/CHUBB/Dependencies2
