<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema 
targetNamespace="http://ei/core/ccm_category" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="CCMCategory">
		<xsd:annotation>
      <xsd:documentation>This element is used for the Chubb Custom Market business.</xsd:documentation>
    </xsd:annotation>
		<xsd:sequence>
			<xsd:element minOccurs="0" name="CCMCategoryCode" type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element identifies the major risk of a Chubb Custom Market Policy.
The corporate table E1T00081 contains the valid values for this element in the "CCM_CAT_C" column.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="CCMCategoryAbbreviation" type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element contains an abbreviated name of the risk category of a Chubb Custom Market policy.
The corporate table E1T00081 contains the valid values for this element in the "CCM_CAT_AB" column.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>