<?xml version="1.0" encoding="UTF-8"?><xsd:schema targetNamespace="http://ei/core/competitor" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="Competitor">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="CompetitorCompanyNumber" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a number assigned to a Competitor.
The E1T00261Competitor Corporate Table contains valid values for this element in the "COMPETR_CO_N" column.
</xsd:documentation>
        </xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0" name="CompetitorCompanyName" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the name of a Competitor.
The E1T00261Competitor Corporate Table contains valid values for this element in the "COMPETR_CO_NA" column.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0" name="CompetitorCompanyMixedCaseName" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the name of a Competitor.
The E1T00261Competitor Corporate Table contains valid values for this element in the "COMPETR_CO_MXC_NA" column.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0" name="CompetitorCompanyConciseName" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>This element contains the name of a Competitor.
The E1T00261Competitor Corporate Table contains valid values for this element in the "COMPETR_CO_CNCS_NA" column.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="CountryAbbreviation" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element is the abbreviation for a country, nation or political state.
The E1T00101 Corporate Table contains valid values for this element in the "CNTRY_AB" column. </xsd:documentation>
        </xsd:annotation>
			</xsd:element>


		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>