<?xml version="1.0" encoding="UTF-8"?><xsd:schema targetNamespace="http://ei/core/document_indexing_group" xmlns:bons1="http://ei/core/document_business_property" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:import namespace="http://ei/core/document_business_property" schemaLocation="DocumentBusinessProperty.xsd"/>
	<xsd:complexType name="DocumentIndexingGroup">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="DocumentRepositoryName" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>This element contains the name of the repository in which the document is stored.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="DocumentRepositoryVersionNumber" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>This element contains the version number of the document in a document repository.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="DocumentBusinessProperty" type="bons1:DocumentBusinessProperty">
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>