<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://ei/core/header">

	<xsd:element name="Header">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="MessageId" type="xsd:string"/>
				<xsd:element name="MessageDateTime" type="xsd:dateTime"/>
				<xsd:element name="MessageName" type="xsd:string"/>
				<xsd:element name="CorrelationId" type="xsd:string"/>
				<xsd:element name="CorporateDataEnrichment" type="xsd:boolean" minOccurs="0"/>
				<xsd:element name="MessageVersion" type="xsd:string"/>
				<xsd:element name="MessageStatus" minOccurs="0">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="Errors" minOccurs="0">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="Error" minOccurs="0" maxOccurs="unbounded">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element name="ErrorCode" type="xsd:string" minOccurs="0"/>
													<xsd:element name="ErrorDescription" type="xsd:string" minOccurs="0"/>
													<xsd:element name="ErrorSeverityLevel" type="xsd:string" minOccurs="0"/>
													<xsd:element name="ErrorSourceIdentifier" type="xsd:string" minOccurs="0"/>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="StatusCode" type="xsd:string" minOccurs="0"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="ConsumerAdapter" minOccurs="0">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="AdapterId" type="xsd:string" minOccurs="0"/>
							<xsd:element name="AdapterName" type="xsd:string" minOccurs="0"/>
							<xsd:element name="AdapterVersion" type="xsd:string" minOccurs="0"/>
							<xsd:element name="AdapterType" type="xsd:string" minOccurs="0"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="MessageHistory" minOccurs="0">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="Recipient" minOccurs="0" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="RecipientMessageName" type="xsd:string" minOccurs="0"/>
										<xsd:element name="RecipientIdentifier" type="xsd:string" minOccurs="0"/>
										<xsd:element name="ReceivedTimestamp" type="xsd:dateTime" minOccurs="0"/>
										<xsd:element name="Duration" type="xsd:long" minOccurs="0"/>
										<xsd:element name="SplitTimes" minOccurs="0" maxOccurs="unbounded">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element name="SplitTimesName" type="xsd:string" minOccurs="0"/>
													<xsd:element name="SplitTimesDuration" type="xsd:long" minOccurs="0"/>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="MessageSecurity">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="UserToken" minOccurs="0">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="UserId" type="xsd:string" minOccurs="0"/>
										<xsd:element name="SystemId" type="xsd:string" minOccurs="0"/>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="SecurityToken" type="xsd:string" minOccurs="0"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>
