<?xml version="1.0" encoding="UTF-8"?><xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://ei/core/identification_information">
	<xsd:complexType name="IdentificationInformation">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="IdNumber" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains an id number which identifies an entity.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="IdModifiedNumber" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a modified version of IdNumber in which spaces and punctuation are removed.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ISOCountryCode" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element is the abbreviation used by the International Standards Organization (ISO) that identifies a country, nation
or political state. The E1T00101 Corporate Table contains valid values for this element in the "ISO_CNTRY_C" column.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="IdIssueDate" type="xsd:date">
				<xsd:annotation>
          <xsd:documentation>This element contains the date the IdNumber was issued.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="IdExpirationDate" type="xsd:date">
				<xsd:annotation>
          <xsd:documentation>This element contains the date the IdNumber expires.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="IdSupplementalInformationText" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains supplemental text regarding the IdNumber.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="IdTypeName" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the type of the id. Some valid values include 'SSN', 'NIE', 'Cedula'.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>