<?xml version="1.0" encoding="UTF-8"?><xsd:schema targetNamespace="http://ei/core/loss_history" xmlns:bons1="http://ei/core/loss_history_cause_of_loss_payment" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:import namespace="http://ei/core/loss_history_cause_of_loss_payment" schemaLocation="LossHistoryCauseOfLossPayment.xsd"/>
	<xsd:complexType name="LossHistory">
		<xsd:sequence>

			<xsd:element maxOccurs="unbounded" minOccurs="0" name="LossHistoryCauseOfLossPayment" type="bons1:LossHistoryCauseOfLossPayment">
			</xsd:element>
			<xsd:element minOccurs="0" name="LossNumber" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a unique number assigned to a loss, this number remains constant.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="LossSequenceNumber" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a sequential number.  It is incremented each time a new loss occurs.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ClaimNumber" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a unique number assigned to the claim.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ClaimLossDate" type="xsd:date">
				<xsd:annotation>
          <xsd:documentation>This element contains the date the loss or accident occured.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ThresholdLossPaidDate" type="xsd:date">
				<xsd:annotation>
          <xsd:documentation>This element contains the date that the loss payments exceeded the threshold amount for chargeability or surcharging as filed in the state.

</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="LossIndividualPaymentIssueDate" type="xsd:date">
				<xsd:annotation>
          
        <xsd:documentation>This element contains the issue date of a loss payment.   This can contain the first or last payment date.
</xsd:documentation>
        </xsd:annotation>
			</xsd:element>


			<xsd:element minOccurs="0" name="LossPaidAmount" type="xsd:decimal">
				<xsd:annotation>
          <xsd:documentation>This element contains the sum of indemnity or loss payments.   In some systems reimbursed deductible receipts or salvage or subrogation receipts are netted out of total loss paid.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>


			<xsd:element minOccurs="0" name="LossDescriptionText" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a text description of the loss.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0" name="LossClaimTypeCode" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a code that identifies the loss type as a risk or subject.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0" name="SourceSystemSourceOfLossCode" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains a code that identifies the cause of loss as it is known by the source system.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="LossCatastropheCode" type="xsd:string">
				<xsd:annotation>
                	
                <xsd:documentation>This element contains a code that identifies if this is a catastrophic loss.
Valid values include 'Y'-Yes, 'N'-No, and 'U'-Unknown.

</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ChubbLossIndicator" type="xsd:boolean">
				<xsd:annotation>
          <xsd:documentation>This element indicates if this is a Chubb Loss.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="FutureLossIndicator" type="xsd:boolean">
				<xsd:annotation>
          <xsd:documentation>This element indicates if a Chubb loss has not yet been applied to the Policy's Rating.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ChargeableLossCode" type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element contains a code that identifies if this is a chargeable loss.
Valid values include 'Y'-Yes, 'N'-No, and 'U'-Unknown.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ChargeableAccidentIndicator" type="xsd:boolean">
				<xsd:annotation>
          <xsd:documentation>This indicates if the accident was chargeable.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="LossViolationSurchargeIndicator" type="xsd:boolean">
				<xsd:annotation>
          <xsd:documentation>This element indicates whether a loss or violation was included in the loss and violation surcharge.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0" name="ExperiencePeriodCode" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>This element if a loss is in the experience period, which is determined by state based rules.  </xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="LossOverThresholdIndicator" type="xsd:boolean">
        <xsd:annotation>
          <xsd:documentation>This element indicates if the loss paid amount has exceeded the threshold.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="SurchargeVehicleNumber" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>This element contains the vehicle number that was surcharged for this loss.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>

			<xsd:element minOccurs="0" name="LossRatingCode" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the code used to identify the detailed information regarding the rating of a particular loss.
</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="SubroReceivedIndicator" type="xsd:boolean">
        <xsd:annotation>
          <xsd:documentation>This element indicated if subrogation was received, if a 3rd party paid for at least part of the claim.  This implies the Insured is nor responsible for the entire loss.
</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="MessageLossHistoryId" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>This element contains an Id assigned for the  lifetime of the message that will be used to identify the Loss History.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="CLUEClaimSequenceNumber" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>This element contains a CLUE assigned sequence number to identify a Claim record.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="CLUEReportRequestNumber" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>This element uniquely identifies a request, by transaction, for a CLUE report.  A CLUE report is obtained from a third party vendor.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="DrivingRecordGIN" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>This element contains an unique driving record number assigned by Chubb, to the driving record data is received from Choicepoint.         </xsd:documentation>
        </xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>