<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ei/core/policy_processing_note"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="PolicyProcessingNote">
		<xsd:annotation>
      
    
    </xsd:annotation>
		<xsd:sequence>

			<xsd:element minOccurs="0" name="PolicyProcessingNoteId"
				type="xsd:integer">
				<xsd:annotation>
          
        
        <xsd:documentation>This element contains a unique identifier for a policy processing note.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="PolicyProcessingNotePriorityNumber" type="xsd:integer">
				<xsd:annotation>
          
        
        <xsd:documentation>This contains a number which indicates the priority of the policy processing note.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="PolicyProcessingNoteCategoryId" type="xsd:integer">
				<xsd:annotation>
          <xsd:documentation>This element contains a unique identifier for the category type.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="PolicyProcessingNoteCategoryName" type="xsd:string">
				<xsd:annotation>
          
        
        <xsd:documentation>This element contains the categorization of the policy processing note.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="PolicyProcessingNoteCategoryPriorityNumber"
				type="xsd:integer">
				<xsd:annotation>
          
        
        <xsd:documentation>This element contains the priority of the category to which this policy processing note belongs.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PolicyProcessingNoteText"
				type="xsd:string">
				<xsd:annotation>
          
        
        <xsd:documentation>This element contains the text note that contains information related to the processing of a policy.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PolicyProcessingNoteRuleId"
				type="xsd:string">
				<xsd:annotation>
          
        
        <xsd:documentation>This element contains a unique identifier for the policy processing note rule.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="PolicyProcessingNotePriorityRankNumber" type="xsd:double">
				<xsd:annotation>
          <xsd:documentation>This element contains the value that identifies the ranking of a particular entry.  Values will be assigned in order to signify importance relative to another rank value.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="PolicyProcessingDisplayOrderNumber" type="xsd:integer">
				<xsd:annotation>
          
        
        <xsd:documentation>This element contains the order in which the policy processing notes should be displayed.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PolicyProcessingNoteDate"
				type="xsd:date"><xsd:annotation><xsd:documentation>This element contains the date of the note.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="PolicyProcessingTitleName"
				type="xsd:string"><xsd:annotation><xsd:documentation>This element contains the title of the note.</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>