<?xml version="1.0" encoding="UTF-8"?><xsd:schema targetNamespace="http://ei/core/policy_processing_information" xmlns:bons0="http://ei/core/risk_rating_group" xmlns:bons2="http:/ei/core/policy_processing_note_set" xmlns:bons3="http://ei/core/policy_processing_data" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:import namespace="http://ei/core/risk_rating_group" schemaLocation="RiskRatingGroup.xsd"/>
    <xsd:import namespace="http://ei/core/policy_processing_data" schemaLocation="PolicyProcessingData.xsd"/>
    <xsd:import namespace="http:/ei/core/policy_processing_note_set" schemaLocation="PolicyProcessingNoteSet.xsd"/>






	<xsd:complexType name="PolicyProcessingInformation">
		<xsd:sequence>

			<xsd:element maxOccurs="unbounded" minOccurs="0" name="PolicyProcessingNoteSet" type="bons2:PolicyProcessingNoteSet">
			</xsd:element>


			<xsd:element maxOccurs="unbounded" minOccurs="0" name="PolicyProcessingData" type="bons3:PolicyProcessingData">
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="RiskRatingGroup" type="bons0:RiskRatingGroup">
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>