<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ei/core/policy_contact_information"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:bons2="http://ei/core/email_information"
	xmlns:bons0="http://ei/core/phone_information">
	<xsd:import schemaLocation="PhoneInformation.xsd"
		namespace="http://ei/core/phone_information">
	</xsd:import>
	<xsd:import schemaLocation="EmailInformation.xsd"
		namespace="http://ei/core/email_information">
	</xsd:import>

	<xsd:complexType name="PolicyContactInformation">
		<xsd:sequence>
			<xsd:element maxOccurs="unbounded" minOccurs="0"
				name="EmailInformation" type="bons2:EmailInformation">
			</xsd:element>
			<xsd:element maxOccurs="unbounded" minOccurs="0"
				name="PhoneInformation" type="bons0:PhoneInformation">
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>