<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ei/core/processing_option"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="ProcessingOption">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="ProcessingOptionName"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element is part of a name/value pair that contains the name of the processing option.  </xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="ProcessingOptionValue"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element is part of a name/value pair that contains the value of the processing option.  Some valid values include a numeric value,  a text value or true/false.</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>