<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
	targetNamespace="http://ei/core/risk_class_grade_information"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="RiskClassGradeInformation">
		<xsd:annotation>
      
    <xsd:documentation>This object contains data from the E0T03811 application reference data table (Commercial Risk Class Codes) owned by Commercial Underwriting.  The table associates a grade with each SIC Code applicable to Commercial Lines, no historical data is maintained.   


</xsd:documentation></xsd:annotation>
		<xsd:sequence>
			<xsd:element minOccurs="0" name="SICCode"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element identifies a major industry classification as determined by the US Federal Government. 
The first two characters of the SIC code are the Major Group.
The last two characters of the SIC code are the Industry Code.  
The E1T00331 Corporate Table contains valid values for the SIC Code(SIC_C), as well as columns for Major Group (SIC_MAJ_GRP_C) and Industry Code (SIC_INDST_C). 
The E1T00321 Corporate Table contains valid values for only the Major Group (SIC_MAJ_GRP).</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="PropertyBusnIntRiskClassGradeCode" type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element contains a code used to identify Chubb's overall Underwriting attitude for the property/business interruption coverage for a particular Standard Industrial Classification.  This element is also known as 
PropertyBusinessInterruptionRiskClassCode.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="FidelityRiskClassGradeCode"
				type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element contains a code used to identify Chubb's overall Underwriting attitude for the Fidelity coverage for a particular Standard Industrial Classification.  This element is also known as FidelityRiskClassCode.
</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="GLPremisesRiskClassGradeCode" type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element contains a code used to identify Chubb's overall Underwriting attitude for the General Liability Premises coverage for a particular Standard Industrial Classification.  This element is also known as GeneralLiabilityPremisesRiskClassCode.
</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="GLProductRiskClassGradeCode" type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element contains a code used to identify Chubb's overall Underwriting attitude for the General Liability Product coverage for a particular Standard Industrial Classification.  This element is also known as GeneralLiabilityProductRiskClassCode.
</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="WCRiskClassGradeCode"
				type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element contains a code used to identify Chubb's overall Underwriting attitude for the Workers Compensation coverage for a particular Standard Industrial Classification.  This element is also known as WorkersCompensationRiskClassCode.
</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="AutoRiskClassGradeCode"
				type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element contains a code used to identify Chubb's overall Underwriting attitude for the Automobile coverage for a particular Standard Industrial Classification.  This element is also known as AutoRiskClassCode.
</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="UmbrellaRiskClassGradeCode"
				type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element contains a code used to identify Chubb's overall Underwriting attitude for the Umbrella coverage for a particular Standard Industrial Classification.  This element is also known as UmbrellaRiskClassCode.
This element is also known as UmbrellaRiskClassCode.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="AllOtherPerilsRiskClassGradeCode" type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element contains a code used to identify Chubb's overall Underwriting attitude for the all others perils coverage for a particular Standard Industrial Classification.  This element is also known as AllOtherPerilsRiskClassCode.
</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="TransitRiskClassGradeCode"
				type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element contains a code used to identify Chubb's overall Underwriting attitude for the transit coverage for a particular Standard Industrial Classification.  This element is also known as TransitRiskClassCode.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="BoilerAndMachineryRiskClassGradeCode" type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element contains a code used to identify Chubb's overall Underwriting attitude for the boiler and machinery coverage for a particular Standard Industrial Classification.  This element is also known as BoilerAndMachineryRiskClassCode.</xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>