<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://ei/core/sic_information">
	<xsd:complexType name="SICInformation">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="SICCode"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element identifies a major industry classification as determined by the US Federal Government. 
The first two characters of the SIC code are the Major Group.
The last two characters of the SIC code are the Industry Code.  
The E1T00331 Corporate Table contains valid values for the SIC Code(SIC_C), as well as columns for Major Group (SIC_MAJ_GRP_C) and Industry Code (SIC_INDST_C). 
The E1T00321 Corporate Table contains valid values for only the Major Group (SIC_MAJ_GRP).</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="SICName"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains the name associated to a particular SIC Code.
The E1T00331 Corporate Table contains valid values for this element in the &quot;SIC_NA&quot; or &quot;SIC_MXC_NA&quot; column. </xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="SICDivisionCode"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This code indentifies a major division of classification for industries as determined by the US Federal Government.
The E1T00331 Corporate Table contains valid values for this element in the &quot;SIC_DIV_C&quot; column. </xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="SICMajorGroupCode"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This code indentifies a major industry group in the standard classification of industries established by the US Department Of Commerce for Statistical Analysis.
The E1T00331 Corporate Table contains valid values for this element in the &quot;SIC_MAJ_GRP_C&quot; column. </xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="SICIndustryCode"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element code indentifies a major industry classification as determined by the US Federal Government.  The first digit represents the industry group and the second digit the industry.
The E1T00331 Corporate Table contains valid values for this element in the &quot;SIC_INDST_C&quot; column. </xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>
