<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
	targetNamespace="http://ei/core/text_analytics_concept_result"
	xmlns:bons1="http://ei/core/text_analytics_concept_term_result"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:import
		namespace="http://ei/core/text_analytics_concept_term_result"
		schemaLocation="TextAnalyticsConceptTermResult.xsd" />
	<xsd:complexType name="TextAnalyticsConceptResult">
		<xsd:sequence>
			<xsd:element maxOccurs="unbounded" minOccurs="0"
				name="TextAnalyticsConceptTermResult"
				type="bons1:TextAnalyticsConceptTermResult">
			</xsd:element>
			<xsd:element minOccurs="0" name="TextAnalyticsConceptName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the name of a text analytics concept.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="TextAnalyticsConceptVersionNumber" type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the version of the text analytics concept.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="TextAnalyticsConceptResultIndicator" type="xsd:boolean">
				<xsd:annotation>
          
        <xsd:documentation>This element contains the result of a text analytics concept that has been run on a text object.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="TextAnalyticsConceptResultValue" type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains data related to the concept that was found in the text during the analysis. </xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0"
				name="TextAnalyticsConceptResultDescription" type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains describes the data related to the concept that was found in the text during the analysis. </xsd:documentation></xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>