<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ei/core/web_application_cookie"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="WebApplicationCookie">
		<xsd:sequence>
			<xsd:element minOccurs="0" name="WebApplicationCookieName"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains the name of the cookie.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="WebApplicationCookieValue"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This application contains the value of the cookie.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="CookieExpiresTimestamp"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the date/time that the cookie expires.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="CookieMaxAgeNumber"
				type="xsd:string">
				<xsd:annotation>
          
        <xsd:documentation>This element contains the age in seconds the cookie should last.</xsd:documentation></xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="CookiePathName"
				type="xsd:string">
				<xsd:annotation>
          <xsd:documentation>This element contains the path prefix the cookie is valid for.</xsd:documentation>
        </xsd:annotation>
			</xsd:element>
			<xsd:element minOccurs="0" name="CookieDomainName"
				type="xsd:string">
				<xsd:annotation><xsd:documentation>This element contains the domain the cookie is valid for.</xsd:documentation></xsd:annotation>
			</xsd:element>


		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>